type: layout
code: m_sipaf.site_details
title: Layout site details
description: Layout pour les details d'un site

layout:
  height_auto: true
  direction: row
  items:
    - type: map
      items:
        - type: object
          display: geojson
          object_code: site
          prefilters: __f__`id_passage_faune = ${o.object(x, 'site').value}`
          popup_fields: __SITE_MAP_POPUP_FIELDS__

    - items:
        - type: breadcrumbs
          flex: "0"
        - code: utils.object_details
          template_params:
            object_code: site
            layout: __SITE_DETAILS_FIELDS__
