type: layout
code: m_sipaf.site_list
title: Layout site list
description: Layout pour la liste de sites

layout:
  height_auto: true
  direction: row
  object_code: site
  items:
    - type: object
      display: filters
      flex: 1
      items: __SITE_FILTERS_FIELDS__
      filter_defs: __SITE_FILTERS_DEFS__

    - type: map
      flex: 2
      items:
        type: object
        display: geojson
        popup_fields: __SITE_MAP_POPUP_FIELDS__

    - flex: 2
      items:
        - type: breadcrumbs
          flex: "0"
        - direction: row
          items:
            - code: utils.button_create
              flex: "0"
            - type: button
              flex: "0"
              icon: download
              description: Télécharger les passages à faune (les filtres sont appliqués)
              href: __f__o.url_export(x, 'm_sipaf.pf')
              hidden: __f__!o.is_action_allowed(x, 'E')
            # - type: button
            #   flex: "0"
            #   icon: upload
            #   color: primary
            #   description: Importer des passage à faune
            #   action:
            #     type: modal
            #     modal_name: import
            #   hidden: __f__!o.is_action_allowed(x, 'C')
            # - type: modal
            #   modal_name: import
            #   items:
            #     title: Importer des passage à faune
            #     type: form
            #     items:
            #       - items:
            #         - key: data_file
            #           type: file
            #           title: Fichier d'import
            #           description: Choisir un fichier à importer
            #         - key: object_code
            #           type: string
            #           default: __f__context.object_code
            #       - direction: row
            #         items:
            #           - type: button
            #             color: primary
            #             title: Valider
            #             description: Valider
            #             action: import
            #             disabled: __f__!(formGroup.valid )
            #           - type: button
            #             color: primary
            #             title: Annuler
            #             description: Annuler
            #             action: close

          flex: "0"
        - type: object
          display: table
          sort: code_passage_faune
          items: __SITE_TABLE_FIELDS__
