type: layout
code: m_sipaf.diagnostic_edit
title: page edit diagnostic
description: page edit diagnostic

aliases:
  - &diag_commons
    - hidden: true
      items:
        - id_diagnostic
        - key: id_passage_faune
          default: __f__context.params.id_passage_faune
    - display: row
      items:
        - date_diagnostic
        - id_organisme
        - id_role
        - commentaire_diagnostic

  - &diag_perturbation_obstacle
    - direction: row
      items:
        - key: nomenclatures_diagnostic_obstacle
          additional_fields:
            - cd_nomenclature
          type: list_form
          multiple: true
          return_object: true
        - key: obstacle_autre
          hidden: __f__!data.nomenclatures_diagnostic_obstacle?.some(n => n.cd_nomenclature == 'AUT')
          required: __f__data.nomenclatures_diagnostic_obstacle?.some(n => n.cd_nomenclature == 'AUT')
    - direction: row
      items:
        - key: nomenclatures_diagnostic_perturbation
          additional_fields:
            - cd_nomenclature
          type: list_form
          multiple: true
          return_object: true
        - key: perturbation_autre
          hidden: __f__!data.nomenclatures_diagnostic_perturbation?.some(n => n.cd_nomenclature == 'AUT')
          required: __f__data.nomenclatures_diagnostic_perturbation?.some(n => n.cd_nomenclature == 'AUT')
    - nomenclatures_diagnostic_ouvrage_hydrau_etat_berge
    - id_nomenclature_diagnostic_ouvrage_hydrau_racc_banq
    - nomenclatures_diagnostic_ouvrage_hydrau_dim
    - commentaire_perturbation_obstacle

  - &diag_amenagement
    - direction: row
      items:
        - key: nomenclatures_diagnostic_amenagement_biodiv
          additional_fields:
            - cd_nomenclature
          type: list_form
          multiple: true
          return_object: true
        - key: amenagement_biodiv_autre
          disabled: __f__!data.nomenclatures_diagnostic_amenagement_biodiv?.some(n => n.cd_nomenclature == 'AUT')
          required: __f__data.nomenclatures_diagnostic_amenagement_biodiv?.some(n => n.cd_nomenclature == 'AUT')
    - items:
        - key: clotures
          type: array
          display: fieldset
          items:
            direction: row
            items:
              - id_nomenclature_clotures_guidage_type
              - key: clotures_guidage_type_autre
                disabled: "__f__!(u.get_cd_nomenclature(data?.id_nomenclature_clotures_guidage_type) == 'AUT')"
                required: "__f__u.get_cd_nomenclature(data?.id_nomenclature_clotures_guidage_type) == 'AUT'"
              - id_nomenclature_clotures_guidage_etat
              - key: clotures_guidage_etat_autre
                disabled: "__f__!(u.get_cd_nomenclature(data?.id_nomenclature_clotures_guidage_etat) == 'AUT')"
                required: "__f__u.get_cd_nomenclature(data?.id_nomenclature_clotures_guidage_etat) == 'AUT'"


  - &diag_synthese
    items:


layout:
  height_auto: true
  items:
    code: utils.object_form
    template_params:
      object_code: diagnostic
      layout:
        overflow: true
        items:
          # - title: Diagnostic
          #   display: fieldset
          #   items: *diag_commons
          # - title: Pertubations / Obstacles
          #   display: fieldset
          #   items: *diag_perturbation_obstacle
          - title: Aménagements
            display: fieldset
            items: *diag_amenagement
          # - title: Synthese
          #   display: fieldset
            # items: *diag_synthese
            