type: layout
code: m_sipaf.site_details
title: Layout site details
description: Layout pour les details d'un site

layout:
  height_auto: true
  direction: row
  items:
    - type: map
      flex: 2
      zoom: 14
      skip_ref_layers: __SKIP_REF_LAYERS__
      items:
        - type: object
          zoom: true
          display: geojson
          object_code: site
          prefilters: __f__`id_passage_faune = ${o.object(x, 'site').value}`
          popup_fields: __SITE_MAP_POPUP_FIELDS__
          bring_to_front: true
          tooltip_permanent: true
        - type: object
          display: geojson
          object_code: synthese
          prefilters: __f__`the_geom_4326 dwithin m_sipaf.pf;${o.object(x, 'site').value};geom;1000`
          popup_fields:
            - date_min
            - dataset.dataset_name
            - taxref.nom_vern
            - nomenclature_bio_condition.label_fr
        - type: object
          hidden: __f__!context.map_params?.bounds_filter_value
          display: geojson
          object_code: ref_geo.point
          module_code: MODULATOR
          title: PK / PR
          activate: false
          zoom_min: 12
          popup_fields:
            - point_code
            - point_name
            - type.type_name
            - key: additional_data.route_dept
              title: axe
            - key: additional_data.gestion
              title: gestion
            - key: additional_data.id_section
              title: section
            - key: additional_data.numero
              title: numero
            - key: additional_data.abscisse
              title: abscisse
          prefilters: |
            __f__{
              const mapBoxFilterValue = context.map_params?.bounds_filter_value;
              return mapBoxFilterValue && `geom_4326 bbox ${mapBoxFilterValue}`;
            }
          style:
            color: orange

    - flex: 3
      items:
        - type: breadcrumbs
          flex: "0"
        - code: utils.object_details
          template_params:
            object_code: site
            layout: __SITE_DETAILS_FIELDS__
