type: layout
code: m_sipaf.diagnostic_edit
title: page edit diagnostic
description: page edit diagnostic

layout:
  height_auto: true
  items:
    code: utils.object_form
    template_params:
      object_code: diagnostic
      layout: __DIAGNOSTIC_FORM_FIELDS__
