type: layout
code: m_sipaf.diagnostic_details
title: page details diagnostic
description: page details diagnostic

layout:
  height_auto: true
  items:
    - code: utils.object_details
      template_params:
        object_code: diagnostic
        layout: __DIAGNOSTIC_DETAILS_FIELDS__
