type: layout
code: m_sipaf.diagnostic_details
title: page details diagnostic
description: page details diagnostic

aliases:
  - &diag_commons
    - hidden: true
      items:
        - id_diagnostic
        - key: id_passage_faune
          default: __f__context.params.id_passage_faune
    - display: row
      items:
        - passage_faune.code_passage_faune
        - passage_faune.nom_usuel_passage_faune
        - date_diagnostic
        - organisme.nom_organisme
        - role.nom_complet
        - commentaire_diagnostic

  - &diag_perturbation_obstacle
    - title: Obstacles
      items:
        - nomenclatures_diagnostic_obstacle.label_fr
        - key: nomenclatures_diagnostic_obstacle.cd_nomenclature
          hidden: true
        - key: obstacle_autre
          hidden: __f__!data.nomenclatures_diagnostic_obstacle?.some(n => n.cd_nomenclature == 'AUT')
    - title: Perturbation
      items:
        - nomenclatures_diagnostic_perturbation.label_fr
        - key: nomenclatures_diagnostic_perturbation.cd_nomenclature
          hidden: true
        - key: perturbation_autre
          hidden: __f__!data.nomenclatures_diagnostic_perturbation?.some(n => n.cd_nomenclature == 'AUT')

    - title: Ouvrage hydrau
      items:
        - nomenclatures_diagnostic_ouvrage_hydrau_etat_berge.label_fr
        - nomenclature_ouvrage_hydrau_racc_banq.label_fr
        - nomenclatures_diagnostic_ouvrage_hydrau_dim.label_fr
        - commentaire_perturbation_obstacle

  - &diag_amenagement
    - title: Aménagements
      direction: row
      items:
        - nomenclatures_diagnostic_amenagement_biodiv.label_fr
        - key: nomenclatures_diagnostic_amenagement_biodiv.cd_nomenclature
          hidden: true
        - key: amenagement_biodiv_autre
          hidden: __f__!data.nomenclatures_diagnostic_amenagement_biodiv?.some(n => n.cd_nomenclature == 'AUT')
    - key: clotures
      type: array
      items:
        direction: row
        items:
          - nomenclature_clotures_guidage_type.label_fr
          - key: clotures_guidage_type_autre
            hidden: "__f__!(u.get_cd_nomenclature(data?.id_nomenclature_clotures_guidage_type) == 'AUT')"
          - nomenclature_clotures_guidage_etat.label_fr
          - key: clotures_guidage_etat_autre
            hidden: "__f__!(u.get_cd_nomenclature(data?.id_nomenclature_clotures_guidage_etat) == 'AUT')"
    - key: vegetation_tablier
      type: array
      items:
        direction: row
        items:
          - nomenclature_vegetation_type.label_fr
          - nomenclature_vegetation_couvert.label_fr
    - key: vegetation_debouche
      type: array
      items:
        direction: row
        items:
          - nomenclature_vegetation_type.label_fr
          - nomenclature_vegetation_couvert.label_fr
    - commentaire_amenagement

  - &diag_synthese
    - nomenclature_franchissabilite.label_fr
    - nomenclature_interet_petite_faune.label_fr
    - nomenclature_interet_grande_faune.label_fr
    - amenagement_faire
    - commentaire_synthese

layout:
  height_auto: true
  items:
    - type: breadcrumbs
      flex: "0"
    - code: utils.object_details
      template_params:
        object_code: diagnostic
        layout:
          display: tabs
          overflow: true
          selected_tab: Aménagement
          items:
            - label: Champs communs
              items: *diag_commons
            - label: Perturbations / Obstacles
              items: *diag_perturbation_obstacle
            - label: Aménagement
              items: *diag_amenagement
            - label: Synthese
              items: *diag_synthese
