type: layout
code: m_sipaf.site_details
title: Layout site details
description: Layout pour les details d'un site

layout:
  height_auto: true
  direction: row
  items:
    - type: map
      flex: 2
      zoom: 14
      items:
        - type: object
          zoom: true
          display: geojson
          object_code: site
          prefilters: __f__`id_passage_faune = ${o.object(x, 'site').value}`
          popup_fields: __SITE_MAP_POPUP_FIELDS__
          bring_to_front: true
          tooltip_permanent: true
        - type: object
          hidden: "__f__!o.config({...context, object_code: 'site'})?.value_xy"
          display: geojson
          object_code: synthese
          prefilters: |
            __f__{
            const xy = o.config({...context, object_code: 'site'})?.value_xy;
            return xy
                ? `the_geom_4326 dwithin ${xy.x};${xy.y};1000`
                : `id_synthese = -1`
            }
          popup_fields:
            - date_min
            - dataset.dataset_name
            - taxref.nom_vern
            - nomenclature_bio_condition.label_fr
            - cor_observers.nom_complet
        - type: object
          display: geojson
          object_code: ref_geo.point
          module_code: MODULATOR
          popup_fields:
            - point_code
            - point_name
            - type.type_name
            - key: additional_data.route_dept
              title: axe
            - key: additional_data.gestion
              title: gestion
            - key: additional_data.id_section
              title: section
            - key: additional_data.numero
              title: numero
            - key: additional_data.abscisse
              title: abscisse
          prefilters: |
            __f__{
              const mapBoxFilterValue = context.map_params?.bounds_filter_value;
              const mapZoom = context.map_params?.zoom;
              return mapBoxFilterValue && mapZoom && mapZoom > 12 && `geom_4326 bbox ${mapBoxFilterValue}` || 'id_point = -1';
            }
          style:
            color: orange

    - flex: 3
      items:
        - type: breadcrumbs
          flex: "0"
        - code: utils.object_details
          template_params:
            object_code: site
            layout: __SITE_DETAILS_FIELDS__
