type: layout
code: m_sipaf.site_edit
title: Layout site edit
description: Layout pour l'édition d'un site

layout:
  height_auto: true
  items:
    code: utils.object_form_map
    template_params:
      object_code: site
      layout: __SITE_FORM_FIELDS__
      zoom: 13
