type: layout
code: m_sipaf.site_edit
title: Layout site edit
description: Layout pour l'édition d'un site

layout:
  height_auto: true
  items:
    code: utils.object_form_map
    template_params:
      object_code: site
      layout: __SITE_FORM_FIELDS__
      zoom: "__f__o.value(x) ? 12 : null"
      skip_ref_layers: __SKIP_REF_LAYERS__
      keep_zoom_center: __f__!o.value(x)
      geojsons:
        - code: m_sipaf.geojson_pkpr