type: schema
code: commons.table_location
title: Schema commons.table_location
description: Définition du schema des 'table_locations'
meta:
    model: geonature.core.gn_commons.models.base.BibTablesLocation
    label: table_location
    label_field_name: table_desc
    genre: F
    unique:
        - schema_name
        - table_name
