type: schema
code: commons.cor_module_jdd
title: Schema commons.cor_module_jdd
description: Définition du schema du lien module jdd

meta:
    model: geonature.core.gn_commons.models.base.CorModuleDataset
    label: module
    label_field_name: id_module
    genre: M
    unique:
        - id_module
        - id_dataset
