type: schema
code: commons.table_location
title: Schema commons.table_location
description: Définition du schema des 'table_locations'
meta:
    schema_code: commons.table_location
    autoschema: true
    model_name: BibTablesLocation
    sql_schema_dot_table: gn_commons.bib_tables_location
    label: table_location
    label_field_name: table_desc
    genre: F
    unique:
        - schema_code
        - table_name
