type: schema
code: ref_geo.area_type
title: Schema ref_geo.area_type
description: Définition du schema des types de zonage de ref_geo

meta:
  model: ref_geo.models.BibAreasTypes
  label: type de geométrie
  label_field_name: type_name
  genre: M
  unique:
    - type_code
