type: schema
code: ref_geo.linear_type
title: Schema ref_geo.linear_type
description: Définition du schema des types de linéaires de ref_geo

meta:
    model: ref_geo.models.BibLinearsTypes
    label: type de linéaire
    label_field_name: type_name
    genre: M
    autoschema: true
    unique:
        - type_code
