type: schema
code: ref_geo.linear
title: Schema ref_geo.linear
description: Définition du schema des linéaires de ref_geo

meta:
    model: ref_geo.models.LLinears
    label: linéaire
    label_field_name: linear_name
    geometry_field_name: geom
    genre: M
    unique:
        - id_type
        - linear_code