type: schema
code: modules.tag
title: Schema modules.tag
description: Définition du schema des tags de sous-modules

meta:
    model: gn_modulator.models.ModuleTags
    label: Tag de modules
    labels: Tags de modules
    label_field_name: name
    genre: M
    unique:
        - code
properties:
    id_module_tag:
        title: Id
    code:
        title: Code du tag de module
    name:
        title: Nom du tag de module
    description:
        title: Description du tag de module
    modules:
        title: modules
