type: use_template
code: m_monitoring_test_2.module
title: Module monitoring test 2
description: Module de test avec entrée par protocole

template_code: m_monitoring.module
params:
  module_code: m_monitoring_test_2
  module_label: Monitest_2
  module_desc: Second module de test monitoring V2
  module_picto: fa-puzzle-piece
  active_frontend: false
