type: use_template
code: m_monitoring_test_2.exemples.data
title: Données exemple m_monitoring_test_2
description: Donnée d'exemple pour le protocole m_monitoring_test_2

template_code: m_monitoring.exemples_site_module.data
params:
  module_code: m_monitoring_test_2