type: object
code: import
title: Reference import
description: Référence pour définitions de 'scénario d'import'

required:
  - type
  - code
  - title
  - description
  - items
properties:
  type:
    type: string
    enum: [import]
  code:
    type: string
  title:
    type: string
  description:
    type: string
  items:
    type: array
    items:
      required:
        - module_code
        - object_code
        # - data
      type: object
      properties:
        module_code:
          type: string
        object_code:
          type: string
        data:
          type: string
          title: Lien vers le fichier (csv) qui contient les données
        pre_process:
          type: string
          title: Lien vers le fichier (sql) qui contient les vue de mapping
        keep_raw:
          type: boolean
          title: "Si l'on souhaite garder la table d'import du fichier csv pour la réutiliser ensuite"

