type: object
code: schema
title: Reference schema
description: Référence pour la definition des schemas
definitions:
  meta: !include schema-meta.reference.yml
required:
  - type
  - code
  - title
  - description
  - meta
  - properties
properties:
  type:
    type: string
    enum: [schema]
  title:
    type: string
  code:
    type: string
  description:
    type: string
  meta:
    $ref: '#/definitions/meta'
  properties:
    type: object
    additionalProperties:
      oneOf:
        - title: propriété commune
          properties:
            type:
              enum:
                - integer
                - string
                - date
                - number
                - date
                - uuid
                - datetime
                - boolean
                - json
            default:
              type: string
            pattern:
              type: string
            title:
              type: string
            format:
              type: string
            description:
              type: string
            labels:
              type: array
              items:
                type: string
            dateFormat:
              type: string
            required:
              type: boolean
            min:
              type: number
            max:
              type: number
            placeholder:
              type: string
          required:
            - type
            - title
          additionalProperties: false
        - title: primary_key
          properties:
            type:
              enum:
                - integer
            title:
              type: string
            description:
              type: string
            primary_key:
              type: boolean
            foreign_key:
              type: boolean
            schema_code:
              type: string
          required:
            - type
            - primary_key
            - title
          additionalProperties: false
        - title: foreign_key
          properties:
            description:
              type: string
            foreign_key:
              type: boolean
            schema_code:
              type: string
            title:
              type: string
            type:
              enum:
                - integer
            required:
              type: boolean
          required:
            - type
            - foreign_key
            - title
            - schema_code
          additionalProperties: false
        - title: id_nomenclature
          properties:
            description:
              type: string
            foreign_key:
              type: boolean
            nomenclature_type:
              type: string
            schema_code:
              type: string
            title:
              type: string
            type:
              enum:
                - integer
            required:
              type: boolean
          required:
            - type
            - schema_code
            - foreign_key
            - nomenclature_type
            - title
          additionalProperties: false
        - title: relation n-1
          properties:
            description:
              type: string
            local_key:
              type: string
            relation_type:
              enum:
                - n-1
            schema_code:
              type: string
            title:
              type: string
            type:
              enum:
                - relation
          required:
            - type
            - title
            - relation_type
            - local_key
            - schema_code
          additionalProperties: false
        - title: relation 1-1
          properties:
            description:
              type: string
            local_key:
              type: string
            relation_type:
              enum:
                - 1-1
            schema_code:
              type: string
            title:
              type: string
            type:
              enum:
                - relation
            backref:
              type: string
          required:
            - type
            - title
            - relation_type
            - local_key
            - schema_code
          additionalProperties: false
        - title: relation 1-n
          properties:
            description:
              type: string
            foreign_key:
              type: string
            relation_type:
              enum:
                - 1-n
            schema_code:
              type: string
            title:
              type: string
            type:
              enum:
                - relation
            backref:
              type: string
          required:
            - type
            - title
            - schema_code
            - relation_type
            - foreign_key
          additionalProperties: false
        - title: relation n-n
          properties:
            description:
              type: string
            foreign_key:
              type: string
            local_key:
              type: string
            relation_type:
              enum:
                - n-n
            schema_dot_table:
              type: string
            nomenclature_type:
              type: string
            schema_code:
              type: string
            cor_schema_code:
              type: string
            title:
              type: string
            trigger:
              type: object
            type:
              enum:
                - relation
            backref:
              type: string
          anyOf:
            - required:
                - type
                - title
                - schema_code
                - schema_dot_table
                - relation_type
            - required:
                - type
                - title
                - schema_code
                - cor_schema_code
                - relation_type
          additionalProperties: false
        - title: geometry
          properties:
            type:
              enum:
                - geometry
            srid:
              type: integer
            geometry_type:
              enum:
                - geometry
                - point
                - polygon
                - linestring
            title:
              type: string
            description:
              type: string
            index:
              type: boolean
            trigger:
              type: object
            required:
              type: boolean
          required:
            - type
            - srid
            - geometry_type
            - title
          additionalProperties: false
        - title: column_property
          properties:
            type:
              type: string
            column_property:
              type: string
            title:
              type: string
          required:
            - type
            - column_property
            - title
          additionalProperties: true
