type: object
code: schema
title: Reference schema
description: Réference pour les schema

definitions:
  meta: !include schema-meta.reference.yml
required:
  - type
  - code
  - title
  - description
  - meta
properties:
  type:
    type: string
    enum: [schema]
  title:
    type: string
  code:
    type: string
  description:
    type: string
  meta:
    $ref: '#/definitions/meta'
  properties:
    type: object
    additionalProperties:
      oneOf:
        - title: auto property
          properties:
            title:
              type: string
          additionalProperties: true
