type: object
code: template
title: Reference template
description: Référence pour les définitions des templates
required:
  - type
  - code
  - title
  - description
  - template
properties:
  type:
    type: string
  code:
    type: string
  title:
    type: string
  description:
    type: string
  defaults:
    type: object
  template:
    type: object
    required:
      - type
      - code
      - title
      - description
    properties:
      code:
        type: string
