data_name: m_monitoring.data
title: catégories test (arbre loge, grotte ?)
items:
    -
        schema_name: m_monitoring.site_category
        items:
            -
                name: Arbre à loge
                code: AL
                description: Données complémentaire sur les site pour les arbres à loge
            -
                name: Grotte
                code: GT
                description: Données complémentaire sur les site pour les grottes
