template:
  name: 'm_monitoring.exemples_template'
data_name: __MODULE_CODE__.exemples
title: ajout de sites d'exemple pour le module (__MODULE_CODE__)
items:
- schema_name: m_monitoring.cor_site_module
  items:
    - { id_module: __MODULE_CODE__, id_site: AL1}
dependencies:
  - m_monitoring.exemples



