type: data
code: m_monitoring.exemples
title: Données exemple monitoring
description: données d'exemple pour monitoring (groupes de site, site, visite)

dependencies:
  - m_monitoring.data
items:
  - schema_code: m_monitoring.site_group
    items:
      - name: Site group 1
        code: SG1
        id_digitiser: admin
        geom:
          type: Polygon
          coordinates:
            - - - 3.90633
                - 44.64349
              - - 3.67132
                - 44.533329
              - - 3.815876
                - 44.481488
              - - 3.967196
                - 44.537547
              - - 3.90633
                - 44.64349
      - name: Site group 2
        code: SG2
        id_digitiser: admin
        geom:
          type: Polygon
          coordinates:
            - - - 3.46399
                - 44.286287
              - - 3.51307
                - 44.499883
              - - 3.738393
                - 44.431426
              - - 3.68262
                - 44.302254
              - - 3.46399
                - 44.286287
      - name: Site group 3
        code: SG3
        id_digitiser: admin
        geom:
          type: Polygon
          coordinates:
            - - - 3.365299
                - 44.417536
              - - 3.355155
                - 44.608013
              - - 3.006867
                - 44.598384
              - - 3.033918
                - 44.347458
              - - 3.365299
                - 44.417536
  - schema_code: m_monitoring.site
    items:
      - name: Arbre à loge 1
        code: AL1
        description: Arbre à loge 1
        id_digitiser: admin
        id_inventor: admin
        id_nomenclature_type_site: "4"
        geom:
          type: Point
          coordinates:
            - 3.6925384212147
            - 44.53985559929568
        id_site_category: AL
        groups:
          - SG1
      - name: Arbre à loge 2
        code: AL2
        description: Arbre à loge 2
        id_digitiser: admin
        id_inventor: admin
        id_nomenclature_type_site: "4"
        geom:
          type: Point
          coordinates:
            - 3.908842837313245
            - 44.61229941522361
        id_site_category: AL
        groups:
          - SG1
      - name: Arbre à loge 3
        code: AL3
        description: Arbre à loge 3
        id_digitiser: admin
        id_inventor: admin
        id_nomenclature_type_site: "4"
        geom:
          type: Point
          coordinates:
            - 3.8279126136029005
            - 44.54720908543729
        id_site_category: AL
        groups:
          - SG1
      - name: Arbre à loge 4
        code: AL4
        description: Arbre à loge 4
        id_digitiser: admin
        id_inventor: admin
        id_nomenclature_type_site: "4"
        geom:
          type: Point
          coordinates:
            - 3.544860549658409
            - 44.47078936657096
        id_site_category: AL
        groups:
          - SG2
      - name: Arbre à loge 5
        code: AL5
        description: Arbre à loge 5
        id_digitiser: admin
        id_inventor: admin
        id_nomenclature_type_site: "4"
        geom:
          type: Point
          coordinates:
            - 3.702746284284442
            - 44.419779234405276
        id_site_category: AL
        groups:
          - SG2
      - name: Arbre à loge 6
        code: AL6
        description: Arbre à loge 6
        id_digitiser: admin
        id_inventor: admin
        id_nomenclature_type_site: "4"
        geom:
          type: Point
          coordinates:
            - 3.6903900094006885
            - 44.359883652319
        id_site_category: AL
        groups:
          - SG2
      - name: Grotte 1
        code: GR1
        description: Grotte 1
        id_digitiser: admin
        id_inventor: admin
        id_nomenclature_type_site: "1"
        geom:
          type: Point
          coordinates:
            - 3.3320580377711155
            - 44.430573553944704
        id_site_category: GT
        groups:
          - SG3
      - name: Grotte 2
        code: GR2
        description: Grotte 2
        id_digitiser: admin
        id_inventor: admin
        id_nomenclature_type_site: "1"
        geom:
          type: Point
          coordinates:
            - 3.333430957202657
            - 44.44528986837578
        id_site_category: GT
        groups:
          - SG3
      - name: Grotte 3
        code: GR3
        description: Grotte 3
        id_digitiser: admin
        id_inventor: admin
        id_nomenclature_type_site: "1"
        geom:
          type: Point
          coordinates:
            - 3.1686806254189563
            - 44.561907953779304
        id_site_category: GT
        groups:
          - SG3
