type: data
code: m_monitoring.category
title: Données de catégories
description: catégories pour monitoring (arbre loge, grotte ?)

items:
  - schema_code: m_monitoring.site_category
    items:
      - name: Arbre à loge
        code: AL
        description: Données complémentaire sur les site pour les arbres à loge
      - name: Grotte
        code: GT
        description: Données complémentaire sur les site pour les grottes
