type: data
code: m_monitoring.exemples_site_module_template
title: template data exemple site module
description: permet d'ajouter une liste de site à un module

items:
  - schema_code: commons.cor_module_jdd
    items:
      - { id_module: __MODULE_CODE__, id_dataset: [m_monitoring_exemple, m_monitoring_exemple]}
  - schema_code: m_monitoring.cor_site_module
    items:
      - { id_module: __MODULE_CODE__, id_site: AL1 }
      - { id_module: __MODULE_CODE__, id_site: AL2 }
      - { id_module: __MODULE_CODE__, id_site: AL3 }
      - { id_module: __MODULE_CODE__, id_site: AL4 }
      - { id_module: __MODULE_CODE__, id_site: AL5 }
      - { id_module: __MODULE_CODE__, id_site: AL6 }
      - { id_module: __MODULE_CODE__, id_site: GR1 }
      - { id_module: __MODULE_CODE__, id_site: GR2 }
      - { id_module: __MODULE_CODE__, id_site: GR3 }
  - schema_code: m_monitoring.visit
    items:
      - id_site: AL1
        date_min: "2023-01-05"
        id_digitiser: admin
        id_module: __MODULE_CODE__
        observers: [admin]
        id_dataset: [m_monitoring_exemple, m_monitoring_exemple]
      - id_site: AL1
        date_min: "2023-01-06"
        id_digitiser: admin
        id_module: __MODULE_CODE__
        observers: [admin]
        id_dataset: [m_monitoring_exemple, m_monitoring_exemple]
  - schema_code: m_monitoring.observation
    items:
      - id_visit: [AL1, __MODULE_CODE__, "2023-01-06"]
        cd_nom: 361617
      - id_visit: [AL1, __MODULE_CODE__, "2023-01-06"]
        cd_nom: 424946
      - id_visit: [AL1, __MODULE_CODE__, "2023-01-05"]
        cd_nom: 582479

dependencies:
  - m_monitoring.exemples
