skip_ref_layers:
  - passages_faune
site_filters_fields:
  display: tabs
  overflow: true
  items:
    - label: Infos
      items:
        - uuid_passage_faune
        - nom_usuel_passage_faune
        - key: nomenclature_ouvrage_specificite
          additional_fields: ["cd_nomenclature"]
        - nomenclatures_ouvrage_materiaux
        - key: pi_ou_ps
          title: Passage inférieur / supérieur
          type: list_form
          items:
            - value: true
              label: Passage supérieur
            - value: false
              label: Passage inférieur
        - title: Possède des diagnostic
          key: diagnostics
          type: boolean

    - label: Localisation
      items:
        - title: Zonage
          items:
            - key: regions
              object_code: ref_geo.area
              module_code: __REF_MODULE_CODE__
              title: Région(s)
              type: list_form
              return_object: true
              multiple: true
              additional_fields:
                - area_code
              filters: |
                __f__data?.infrastructures?.length
                  ? `linears.groups.id_group in ${data.infrastructures.join(";")}`
                  : null
              area_type: REG
              sort: area_name

            - key: departements
              object_code: ref_geo.area
              module_code: __REF_MODULE_CODE__
              title: Département(s)
              type: list_form
              reload_on_search: true
              multiple: true
              area_type: DEP
              return_object: true
              additional_fields:
                - area_code
              label_field_name: code_name
              sort: code_name
              filters: |
                __f__{
                  const filters = [];

                  if (data?.regions?.length > 0) {
                    const f = `area_code in ${data.regions.map(r => u.departementsForRegion(r.area_code).join(';')).join(';')}`;
                    filters.push(f);
                  }

                  if (data?.infrastructures?.length > 0) {
                    const f = `linears.groups.id_group in ${data.infrastructures.join(";")}`;
                    filters.push(f);
                  }

                  return filters.join(',')
                }

            - key: communes
              object_code: ref_geo.area
              module_code: __REF_MODULE_CODE__
              reload_on_search: true
              multiple: true
              title: Commune(s)
              type: list_form
              area_type: COM
              label_field_name: name_code
              filters: |
                __f__{
                  const filters = [];

                  if (data?.departements?.length) {
                    const f = data.departements.map(
                      d => `area_code like ${d.area_code}%`
                    ).join(',|,');
                    filters.push(`[,${f},]`);
                  }

                  if (data?.regions?.length > 0) {
                    const f = data.regions.map(
                      r => u.departementsForRegion(r.area_code)
                        .map(departementCode => `area_code like ${departementCode}%`)
                        .join(',|,')
                    ).join(',|,');
                    filters.push(`[,${f},]`);
                  }

                  if (data?.infrastructures?.length > 0) {
                    const f = `linears.groups.id_group in ${data.infrastructures.join(";")}`;
                    filters.push(f);
                  }

                  return filters.join(',');
                }
              sort: area_name
        - title: Réseau
          items:
            - key: infrastructure_types
              title: Type(s) d'infrastructure
              type: list_form
              multiple: true
              object_code: ref_geo.linear_type
              module_code: __REF_MODULE_CODE__
              sort: type_name
              reload_on_search: true
              page_size: 20

            - key: infrastructures
              title: Infrastructure(s)
              type: list_form
              object_code: ref_geo.linear_group
              module_code: __REF_MODULE_CODE__
              multiple: true
              sort: code*
              reload_on_search: true
              filters: |
                __f__{

                  if(!data) {
                    return "";
                  };

                  const filters = [];

                  if (data.infrastructure_types?.length) {
                    const f = `linears.id_type in ${data.infrastructure_types.join(';')}`;
                    filters.push(f);
                  };

                  let z_values = data.communes?.length
                    ? data.communes
                    : data.departements?.length
                    ? data.departements.map(v => v.id_area)
                    : data.regions?.length
                    ? data.regions.map(v => v.id_area)
                    : null
                  ;

                  if (z_values) {
                    const f = `linears.areas.id_area in ${z_values.join(';')}`
                    filters.push(f);
                  };

                  return filters.join(',');

                }
              page_size: 20

site_filters_defs:
  uuid_passage_faune:
    type: "~"
  nom_usuel_passage_faune:
    type: "~"
  code_ouvrage_gestionnaire:
    type: "~"
  regions:
    field: areas.id_area
    key: id_area
  departements:
    field: areas.id_area
    key: id_area
  communes:
    field: areas.id_area
  infrastructures:
    field: linears.groups.id_group
  infrastructure_types:
    field: linears.type.id_type
  nomenclatures_ouvrage_materiaux:
    field: nomenclatures_ouvrage_materiaux.id_nomenclature
    key: id_nomenclature
  nomenclatures_ouvrage_specificite:
    field: nomenclatures_ouvrage_specificite.id_nomenclature
    key: id_nomenclature
  diagnostics:
    type: any

site_table_fields:
  - key: id_passage_faune
    hidden: true
  - uuid_passage_faune
  - nom_usuel_passage_faune
  - label_infrastructures
  - label_communes

site_map_popup_fields:
  - id_passage_faune
  - uuid_passage_faune
  - nom_usuel_passage_faune
  - nomenclatures_ouvrage_type.label_fr
  - label_infrastructures

site_details_fields:
  display: tabs
  overflow: true
  items:
    - label: Propriétés
      items:
        - title: Informations
          display: fieldset
          items:
            - direction: row
              items:
                - code_ouvrage_gestionnaire
                - nom_usuel_passage_faune
                - uuid_passage_faune
            - direction: row
              items:
                - date_creation_ouvrage
                - issu_requalification
                - date_requalification_ouvrage
                - key: digitiser.nom_complet
                  title: Numerisateur
        - display: fieldset
          key: actors
          type: array
          items:
            direction: row
            items:
              - organisme.nom_organisme
              - nomenclature_type_actor.label_fr
        - direction: row
          items:
            - title: Référentiel
              display: fieldset
              items:
                - items:
                    - label_infrastructures
                    - title: Largeur de la voie (m)
                      key: linears.additional_data.largeur
                    - label_communes
                    - label_departements
                    - label_regions
            - title: Localisation
              display: fieldset
              items:
                - direction: row
                  items:
                    - geom_x
                    - geom_y
                - items:
                    - pk
                    - pr
                    - pr_abs
        - title: Caractéristiques
          display: fieldset
          items:
            - direction: row
              items:
                - nomenclature_ouvrage_specificite.label_fr
                - key: nomenclature_ouvrage_specificite.cd_nomenclature
                  hidden: true
                - nomenclatures_ouvrage_materiaux.label_fr
            - direction: row
              items:
                - nomenclatures_ouvrage_type.label_fr
                - key: nomenclatures_ouvrage_type.cd_nomenclature
                  hidden: true
                - key: ouvrage_type_autre
                  hidden: __f__!data?.nomenclatures_ouvrage_type?.some(n => n.cd_nomenclature == 'AUT')
            - direction: row
              items:
                - pi_ou_ps
                - ouvrage_hydrau
        - display: fieldset
          key: usages
          hidden: __f__data.nomenclature_ouvrage_specificite.cd_nomenclature == "SPE"
          type: array
          items:
            direction: row
            items:
              - nomenclature_usage_type.label_fr
              - detail_usage
              - commentaire
              - key:
                hidden: true
        - display: fieldset
          title: Objectifs
          direction: row
          items:
            - nomenclatures_ouvrage_categorie.label_fr
            # - taxons.nom_vern
        - title: Dimensions
          display: fieldset
          items:
            - direction: row
              items:
                - largeur_ouvrage
                - hauteur_ouvrage
                - longueur_franchissement
            - direction: row
              items:
                - largeur_dispo_faune
                - hauteur_dispo_faune
                - diametre
        - title: Banquette (Ouvrages hydrauliques)
          display: fieldset
          hidden: "__f__!data?.ouvrage_hydrau"
          items:
            - direction: row
              items:
                - nomenclature_ouvrage_hydrau_position.label_fr
                - nomenclature_ouvrage_hydrau_banq_caract.label_fr
                - nomenclature_ouvrage_hydrau_banq_type.label_fr
                - ouvrag_hydrau_tirant_air
    - label: __f__`Médias (${data?.medias?.length || 0})`
      items:
        title: '__f__data?.medias?.length ? "" : "Aucun média pour ce passage faune"'
        items:
          - type: medias
            key: medias

    - label: __f__o.tab_label(x)
      object_code: diagnostic
      hidden: __f__!o.object(x, 'site').value
      items:
        - code: utils.button_create
          flex: "0"
        - type: object
          display: table
          items:
            - date_diagnostic
            - organisme.nom_organisme
            - role.nom_complet
          prefilters: __f__`id_passage_faune = ${o.object(x, 'site').value}`
          sort: date_diagnostic-

    - label: __f__o.tab_label(x)
      object_code: synthese
      items:
        - type: object
          display: table
          prefilters: __f__`the_geom_4326 dwithin m_sipaf.pf;${o.object(x, 'site').value};geom;1000`
          actions:
            R:
              url: "#/synthese/occurrence/<id>"
              title: Liens vers le module de synthese
          items:
            - date_min
            - dataset.dataset_name
            - taxref.nom_vern
            - nomenclature_bio_condition.label_fr
            - cor_observers.nom_complet
          sort: date_min-

site_form_fields:
  display: tabs
  overflow: true
  items:
    - label: Propriétés
      items:
        - type: message
          hidden: __f__(data && data[o.geometry_field_name(x)])
          html: Veuillez saisir une géométrie sur la carte
          class: warning
        - hidden: true
          items:
            - key: id_digitiser
              default: __f__context.current_user?.id_role
            - geom
            - key: id_passage_faune
              required: false
        - title: Informations
          display: fieldset
          items:
            - direction: row
              items:
                - uuid_passage_faune
                - code_ouvrage_gestionnaire
                - nom_usuel_passage_faune
            - direction: row
              items:
                - date_creation_ouvrage
                - issu_requalification
                - date_requalification_ouvrage
        - title: Acteurs
          type: array
          key: actors
          display: fieldset
          items:
            direction: row
            items:
              - id_organism
              - id_nomenclature_type_actor
        - title: Localisation
          display: fieldset
          items:
            - direction: row
              items:
                - pk
                - pr
                - pr_abs
        - title: Caractéristiques
          display: fieldset
          items:
            - direction: row
              items:
                - key: pi_ou_ps
                  type: list_form
                  items:
                    - value: true
                      label: Passage supérieur
                    - value: false
                      label: Passage inférieur
                - ouvrage_hydrau
            - direction: row
              items:
                - key: nomenclatures_ouvrage_type
                  type: list_form
                  multiple: true
                  return_object: true
                  additional_fields: ["cd_nomenclature"]
                - key: ouvrage_type_autre
                  description: __f__data?.nomenclatures_ouvrage_type?.some(n => n.cd_nomenclature == 'AUT')
                  type: string
                  hidden: __f__!data?.nomenclatures_ouvrage_type?.some(n => n.cd_nomenclature == 'AUT')
                  required: __f__data?.nomenclatures_ouvrage_type?.some(n => n.cd_nomenclature == 'AUT')
            - direction: row
              items:
                - key: nomenclature_ouvrage_specificite
                  additional_fields: ["cd_nomenclature"]
                  return_object: true
                  type: list_form
                - key: nomenclatures_ouvrage_materiaux
                  type: list_form
                  multiple: true
                  return_object: true
        - title: Usages
          disabled: __f__data.nomenclature_ouvrage_specificite.cd_nomenclature == "SPE"
          type: array
          key: usages
          display: fieldset
          items:
            direction: row
            items:
              - id_nomenclature_usage_type
              - detail_usage
              - commentaire
        - title: Objectifs
          display: fieldset
          direction: row
          items:
            - key: nomenclatures_ouvrage_categorie
              type: list_form
              multiple: true
              return_object: true
            # - key: taxons
            #   type: list_form
            #   schema_code: tax.taxsearch
            #   multiple: true
            #   return_object: true
            #   reload_on_search: true
            #   page_size: 20

        - title: Dimensions
          display: fieldset
          items:
            - direction: row
              items:
                - largeur_ouvrage
                - hauteur_ouvrage
                - longueur_franchissement
            - direction: row
              items:
                - largeur_dispo_faune
                - hauteur_dispo_faune
                - diametre
        - title: Banquette
          hidden: "__f__!data?.ouvrage_hydrau"
          display: fieldset
          items:
            - direction: row
              items:
                - key: id_nomenclature_ouvrage_hydrau_position
                  type: list_form
                - key: id_nomenclature_ouvrage_hydrau_banq_type
                  type: list_form
            - direction: row
              items:
                - key: id_nomenclature_ouvrage_hydrau_banq_caract
                  type: list_form
                - ouvrag_hydrau_tirant_air
    - label: __f__ `Médias (${data?.medias?.length || 0})`
      items:
        items:
          - hidden: __f__!data?.medias?.some(m => !m.title_fr)
            type: message
            class: warning
            html: Le champs 'Titre' du média est obligatoire
          - type: dyn_form
            key: medias
            type_widget: medias
            schema_dot_table: pr_sipaf.t_passages_faune
            details: []

diagnostic_table_fields:
  - date_diagnostic
  - passage_faune.uuid_passage_faune
  - organisme.nom_organisme
  - role.nom_complet
