type: layout
code: utils.button_create
title: boutton create
description: Bouton 'nouveau, ajouter', destiné aux tableaux de monitoring
layout:
  hidden: __f__!o.is_action_allowed(x, 'C')
  action: create
  type: button
  icon: add
  color: primary
  description: __f__o.label_create(x)
  flex: "0"
