type: layout
code: utils.buttons_filter
title: bouttons filter
description: Boutons rechercher + reset filters

layout:
  flex: "0"
  direction: row
  items:
    - flex: "0"
      type: button
      color: error
      icon: refresh
      description: Réinitialiser filtres
      action: clear-filters
    - flex: "0"
      type: button
      color: success
      title: Rechercher
      icon: done
      description: Effectuer une recherche avec les filtre définis ci-dessus
      action: filter
