type: layout
code: utils.buttons_form
title: bouttons form
description: Bouton 'valider + annuler + supprimer', destiné aux formulaires de monitoring
layout:
  flex: "0"
  direction: row
  items:
    - flex: "0"
      type: button
      color: primary
      title: Annuler
      icon: refresh
      description: "Annuler l'édition"
      action: cancel
    - flex: "0"
      type: button
      color: success
      title: Valider
      icon: done
      description: Enregistrer le contenu du formulaire
      action: submit
      disabled: __f__!formGroup.valid
    - flex: "0"
      type: button
      color: warn
      title: Supprimer
      icon: delete
      description: __f__o.label_delete(x)
      hidden: __f__!o.is_action_allowed(x, 'D')
      action:
        type: modal
        modal_name: delete
    - code: utils.modal_delete
