type: layout
code: utils.object_form
title: Formulaire pour un object (sans carte)
args:
  object_code: object concerné par le Formulaire
  layout: layout des champs du formulaire

layout:
  type: object
  object_code: __OBJECT_CODE__
  items:
    type: form
    title: __f__o.title_create_edit(x)
    items:
      - overflow: true
        items: __LAYOUT__
      - code: utils.buttons_form
        flex: "0"
