type: layout
code: utils.import
title: layout du composant d'import
description: layout du composant d'import
layout:
  title: __f__`Importer ${o.des_labels(x, 'C')}`
  # hidden: __f__!(o.is_action_allowed(x))
  type: form
  items:
    - items:
        - type: message
          html: __f__data.importMsg?.html
          class: __f__data.importMsg?.class
          hidden: __f__!data.importMsg
        - hidden: true
          items:
            - key: importMsg
            - key: object_code
              type: string
              hidden: true
              default: __f__context.object_code
        - title: import
          display: fieldset
          items:
            - key: data_file
              type: file
              title: Fichier d'import
              required: __f__!data.tables?.data
              description: Choisir un fichier à importer
        - title: Options additionnelles
          display: fieldset
          type: dict
          items:
            - key: options.enable_update
              title: "Autoriser les mises à jour"
              type: boolean
              default: __f__false

    - direction: row
      items:
        - type: button
          color: primary
          title: Valider
          description: Valider
          action: import
          disabled: __f__!(formGroup.valid )
        - type: button
          color: primary
          title: Annuler
          description: Annuler
          action: close
