meta:
    schema_name: meta.ca
    unique:
        - acquisition_framework_name
    sql_schema_dot_table: gn_meta.t_acquisition_frameworks
    model_name: TAcquisitionFramework
    label: "cadre d 'acquisition"
    labels: "cadre d'acquistion"
    label_field_name: truc
    genre: M
    autoschema: true
