type: schema
code: meta.ca
title: Schema meta.ca
description: Définition du schema des cadres d'acquistion

meta:
  schema_code: meta.ca
  unique:
    - acquisition_framework_name
  model: geonature.core.gn_meta.models.TAcquisitionFramework
  label: "cadre d'acquisition"
  labels: "cadre d'acquistion"
  label_field_name: acquisition_framework_name
  genre: M
  autoschema: true
  properties:
    acquisition_framework_name:
      title: Nom du cadre d'acquisition