type: schema
code: meta.jdd
title: Schema meta.jdd
description: Définition du schema des jeux de données

meta:
  unique:
    - unique_dataset_id
  model: geonature.core.gn_meta.models.TDatasets
  label: jeu de données
  labels: jeux de données
  label_field_name: dataset_shortname
  title_field_name: dataset_desc
  genre: M
properties:
  dataset_name:
    title: Nom du jeu de données
  acquisition_framework:
    title: Cadre d'acquisition
table:
  columns:
    - acquisition_framework.acquisition_framework_name
    - dataset_name
    - dataset_desc
