type: schema
code: m_sipaf.diag
title: schema diagnostic passage faune
description: schema pour les diagnostics des passages à faune

meta:
    autoschema: true
    model: m_sipaf.models.Diagnostic
    module_code: m_sipaf
    genre: M
    label: diagnostic
    label_field_name: date_diagnostic
    unique:
        - id_passage_faune
        - date_diagnostic
        - id_organism
    unique_in_db: true
properties:
    date_diagnostic:
        title: Date
    id_role:
        title: Agent
    id_organisme:
        title: Organisme
    comment:
        title: Commentaire
    nomenclatures_diagnostic_obstacle:
        title: Obstacle(s)
    obstacle_autre:
        title: Obstacle autre