type: layout
code: m_monitoring.site_filters
title: layout pour les filtres des sites

aliases:
  - &filters_departement |
    __f__{
        return data.region
        ? `area_code in ${utils.departementsForRegion(data.region.area_code).join(';')}`
        : null
    }

  - &filters_commune |
    __f__{
        if (data.departement) {
            return `area_code like ${data.departement.area_code}%`
        }
        if (data.region) {
            return utils.departementsForRegion(data.region.area_code)
                .map(departementCode => `area_code like ${departementCode}%`)
                .join(',|,')
        }
    }

defaults:

  info_filters:
    label: Infos
    items:
      - code
      - name
      - id_site_category

  localisation_filters:
    label: Localisation
    items:
      - key: region
        title: Région
        type: list_form
        return_object: "true"
        additional_fields:
          - area_code
        area_type: REG
        sort: area_name

      - reload_on_search: true
        return_object: true
        key: departement
        title: Département
        type: list_form
        area_type: DEP
        additional_fields:
          - area_code
        label_field_name: code_name
        sort: code_name
        filters: *filters_departement

      - reload_on_search: true
        key: commune
        title: Commune
        type: list_form
        area_type: COM
        label_field_name: name_code
        filters: *filters_commune
        sort: area_name

      - title: Infrastructure
        key: infrastructure
        type: list_form
        object_code: ref_geo.linear_group
        module_code: MODULES
        filters: linears.type.type_code = RTE
        sort: name
        reload_on_search: true
        page_size: 10

  additional_filters:
    hidden: true


layout:
  display: tabs
  items:
    - __INFO_FILTERS__
    - __LOCALISATION_FILTERS__
    - __ADDITIONAL_FILTERS__


