layout_name: m_monitoring.site_list
height_auto: true
direction: row
items:
    -
        type: object
        display: filters
        key: site
    -
        flex: 2
        type: map
        items:
            -
                type: object
                display: geojson
                key: site
            -
                type: object
                display: geojson
                key: site_group
    -
        flex: 2
        items:
            -
                flex: '0'
                type: breadcrumbs
            -
                display: tabs
                items:
                    -
                        label: '__f__`Sites (${data.site.filtered}/${data.site.total})`'
                        items:
                            -
                                key: site
                                type: button
                                title: Ajouter un nouveau site
                                flex: '0'
                                icon: add
                                color: primary
                                action: create
                            -
                                key: site
                                type: object
                                display: table
                    -
                        label: '__f__`Groupes de site (${data.site_group?.filtered}/${data.site_group?.total})`'
                        title: Groupes de sites
                        type: object
                        display: table
                        key: site_group
