layout_name: m_protocol_test.observation_details
height_auto: true
items:
    -
        type: breadcrumbs
        flex: '0'
    -
        type: object
        display: properties
        key: observation
