type: schema
code: perm.filter
title: Schema perm.filter
description: Définition du schema des filtres

meta:
  autoschema: true
  model_name: TFilters
  sql_schema_dot_table: gn_permissions.t_filters
  label: filtre
  label_field_name: label_filter
  genre: M
  unique:
    - value_filter
