type: schema
code: perm.object
title: Schema perm.object
description: Définition du schema des object de permission

meta:
  schema_code: perm.object
  autoschema: true
  model_name: TObjects
  sql_schema_dot_table: gn_permissions.t_objects
  label: object
  label_field_name: label_object
  genre: M
  unique:
    - code_object
