type: schema
code: perm.object
title: Schema perm.object
description: Définition du schema des object de permission

meta:
  schema_code: perm.object
  model: geonature.core.gn_permissions.models.PermObject
  label: object
  label_field_name: label_object
  genre: M
  unique:
    - code_object
