module_details_fields:
  - module_code
  - module_label
  - module_desc

site_filters_fields:
  display: tabs
  items:
    - label: Infos
      items:
        - code
        - name
        - id_site_category
    - label: Localisation
      items:
        - key: region
          title: Région
          type: list_form
          return_object: "true"
          additional_fields:
            - area_code
          area_type: REG
          sort: area_name

        - key: departement
          title: Département
          type: list_form
          reload_on_search: true
          area_type: DEP
          return_object: true
          additional_fields:
            - area_code
          label_field_name: code_name
          sort: code_name
          filters: |
            __f__data?.region
              ? `area_code in ${utils.departementsForRegion(data.region.area_code).join(';')}`
              : null

        - key: commune
          reload_on_search: true
          title: Commune
          type: list_form
          area_type: COM
          label_field_name: name_code
          filters: |
            __f__data?.departement
              ? `area_code like ${data.departement.area_code}%`
              : data?.region
                ? utils.departementsForRegion(data.region.area_code)
                    .map(departementCode => `area_code like ${departementCode}%`)
                    .join(',|,')
                : null
          sort: area_name

        - key: infrastructure
          title: Infrastructure
          type: list_form
          object_code: ref_geo.linear_group
          module_code: MODULES
          filters: linears.type.type_code = RTE
          sort: name
          reload_on_search: true
          page_size: 10

site_filters_defs:
  category:
    field: category.id_category
  region:
    field: areas.id_area
    key: id_area
  departement:
    field: areas.id_area
    key: id_area
  commune:
    field: areas.id_area
  infrastructure:
    field: linears.id_linear

site_form_fields:
  - hidden: true
    items:
      - id_site
  - code
  - name
  - description
  - key: id_site_category
    type: list_form
    title: Catégorie de site
    object_code: category
    module_code: m_monitoring
  - id_nomenclature_type_site
  - ownership

site_table_fields:
  - code
  - name
  - category.name
  - nb_visits
  - last_visit_date_min

site_map_popup_fields:
  - code
  - name
  - description
  - nomenclature_type_site.label_fr
  - category.name
  - nb_visits
  - last_visit_date_min

site_details_fields:
  - hidden: true
    items:
      - id_site
      - ownership
  - code
  - name
  - description
  - nb_visits

visit_table_fields:
  - site.name
  - date_min
  - nb_observations
  - digitiser.nom_complet
  - dataset.dataset_name
  - observers.nom_complet
  - module.module_label

visit_details_fields:
  - site.name
  - module.module_label
  - date_min
  - nb_observations
  - digitiser.nom_complet
  - dataset.dataset_name
  - dataset.acquisition_framework.acquisition_framework_name
  - module.module_label
  - observers.nom_complet

visit_form_fields:
  - hidden: true
    items:
      - id_site
      - id_visit
      - id_module
      - key: id_digitiser
        default: __f__context.current_user?.id_role
        hidden: true
  - key: date_min
    default: __f__utils.today()
  - date_max
  - key: id_module
    type: list_form
    title: Protocole
    schema_code: commons.module
    filters: "__f__`sites.id_site = ${context.params.id_site}`"
  - key: id_dataset
    type: list_form
    title: "__f__data.id_module ? 'Jeu de données' : 'Jeu de données (Veuillez entrer un protocole)'"
    schema_code: meta.jdd
    page_size: 10
    reload_on_search: true
    filters: __f__data.id_module && `modules.id_module = ${data.id_module}`
    disabled: __f__!data.id_module
  - key: observers
    type: list_form
    title: Observateurs
    schema_code: user.role
    multiple: true
    return_object: true
    filters: groupes.listes.code_liste = obsocctax

observation_table_fields:
  - taxon.nom_vern
  - visit.site.name
  - visit.date_min
  - visit.observers.nom_complet

observation_details_fields:
  - visit.date_min
  - taxon.nom_vern
  - visit.site.name
  - visit.dataset.dataset_name
  - visit.observers.nom_complet

observation_form_fields:
  - hidden: true
    items:
      - id_observation
      - id_visit
      - key: id_digitiser
        default: __f__context.current_user?.id_role
  - key: cd_nom
    type: dyn_form
    type_widget: taxonomy
    attribut_label: Espèce
    type_util: taxonomy
    required: true
