type: module
code: m_monitoring.site_template
title: "Module monitoring"
description: "Module monitoring, apporte les schemas des sites, visites, etc..."

config_defaults: !include m_monitoring.site_template.module-tempate_defaults.yml

module:
  module_label: __MODULE_LABEL__
  module_desc: __MODULE_DESC__
  module_picto: fa-puzzle-piece
  active_frontend: true
objects:
  site:
    cruved: CRUD
    schema_code: m_monitoring.site
  visit:
    cruved: CRUD
    schema_code: m_monitoring.visit
  site_group:
    cruved: CRUD
    schema_code: m_monitoring.site_group
    map:
      style:
        color: red
  observation:
    cruved: CRUD
    schema_code: m_monitoring.observation
  module:
    cruved: R
    schema_code: commons.module
  category:
    cruved: R
    schema_code: m_monitoring.site_category

tree:
  site:
    visit:
      observation:

pages_definition:
  site:
    list:
      layout:
        code: m_monitoring.site_list
      root: true
    details:
      layout:
        code: m_monitoring.site_details
    create:
      layout:
        code: m_monitoring.site_edit
    edit:
      layout:
        code: m_monitoring.site_edit

  visit:
    details:
      layout:
        code: m_monitoring.visit_details
    edit:
      layout:
        code: m_monitoring.visit_edit
    create:
      layout:
        code: m_monitoring.visit_edit
  observation:
    details:
      layout:
        code: m_monitoring.observation_details
    edit:
      layout:
        code: m_monitoring.observation_edit
    create:
      layout:
        code: m_monitoring.observation_edit

  # site_group_create:
  #   url: site_group_create
  #   layout:
  #     code: m_monitoring.site_group_edit

  # site_group_details:
  #   url: site_group_details/:id_site_group
  #   layout:
  #     code: m_monitoring.site_group_details
  #   objects:
  #     site_group:
  #       value: ":id_site_group"
  #       prefilters: id_site_group = :id_site_group
  #     site:
  #       prefilters: groups.id_site_group = :id_site_group
  #     visit:
  #       prefilters: site.groups.id_site_group = :id_site_group
  # site_group_edit:
  #   url: site_group_edit/:id_site_group
  #   layout:
  #     code: m_monitoring.site_group_edit
  #   objects:
  #     site_group:
  #       value: ":id_site_group"
