type: module
code: m_monitoring.protocol_template
title: Template de Module de type protocole monitoré
description: Template de protocole monitoring (entrée par module)

config_defaults: !include m_monitoring.site_template.module-tempate_defaults.yml

template_defaults:
  module_picto: fa-puzzle-piece
  active_frontend: false

module:
  module_label: __MODULE_LABEL__
  module_desc: __MODULE_DESC__
  module_picto: __MODULE_PICTO__
  active_frontend: __ACTIVE_FRONTEND__
dependencies:
  - m_monitoring
params:
  id_module:
    object_code: module
    value:
      module_code: __MODULE_CODE__
objects:
  module:
    schema_code: commons.module
    cruved: RU
  jdd:
    schema_code: meta.jdd
    prefilters: "modules.module_code = __MODULE_CODE__"
    cruved: R
  site:
    schema_code: m_monitoring.site
    prefilters: "modules.module_code = __MODULE_CODE__"
    cruved: CRUD
  visit:
    schema_code: m_monitoring.visit
    prefilters: "module.module_code = __MODULE_CODE__"
    cruved: CRUD
  observation:
    schema_code: m_monitoring.observation
    prefilters: "visit.module.module_code = __MODULE_CODE__"
    cruved: CRUD
tree:
  module:
    site:
      visit:
        observation: null
pages_definition:
  module:
    details:
      layout:
        code: m_monitoring.module_details
      root: true
    edit:
      layout:
        code: m_monitoring.module_edit
  site:
    details:
      layout:
        code: m_monitoring.site_details
    edit:
      layout:
        code: m_monitoring.site_edit
    create:
      layout:
        code: m_monitoring.site_edit

  visit:
    details:
      layout:
        code: m_monitoring.visit_details
    edit:
      layout:
        code: m_monitoring.visit_edit
    create:
      layout:
        code: m_monitoring.visit_edit

  observation:
    details:
      layout:
        code: m_monitoring.observation_details
    edit:
      layout:
        code: m_monitoring.observation_edit
    create:
      layout:
        code: m_monitoring.observation_edit
