type: module
code: m_monitoring
title: "Module monitoring"
description: "Module monitoring, apporte les schemas des sites, visites, etc..."

module:
  module_label: Gestionnaire de sites
  module_desc: Module de gestion de sites. (Vers une version 2 du module monitoring)
  module_picto: fa-puzzle-piece
  active_frontend: true
objects:
  site:
    cruved: CRUD
    schema_code: m_monitoring.site
    map:
      bring_to_front: true
  visit:
    cruved: CRUD
    schema_code: m_monitoring.visit
  site_group:
    cruved: CRUD
    schema_code: m_monitoring.site_group
    map:
      style:
        color: red
  observation:
    cruved: CRUD
    schema_code: m_monitoring.observation
  module:
    cruved: R
    schema_code: commons.module
  category:
    cruved: R
    schema_code: m_monitoring.site_category

tree:
  site:
    visit:
      observation:

pages_definition:
  site:
    list:
      root: true
    details:
      objects:
        visit:
          prefilters: id_site = :id_site
        module:
          prefilters: sites.id_site = :id_site
    create:
      layout:
        code: m_monitoring.site_edit
    edit: {}
  visit:
    details:
      objects:
        observation:
          prefilters: id_visit = :id_visit
    edit: {}
    create:
      layout:
        code: m_monitoring.visit_edit
  observation:
    details: {}
    edit: {}
    create:
      layout:
        code: m_monitoring.observation_edit

  # site_group_create:
  #   url: site_group_create
  #   layout:
  #     code: m_monitoring.site_group_edit

  # site_group_details:
  #   url: site_group_details/:id_site_group
  #   layout:
  #     code: m_monitoring.site_group_details
  #   objects:
  #     site_group:
  #       value: ":id_site_group"
  #       prefilters: id_site_group = :id_site_group
  #     site:
  #       prefilters: groups.id_site_group = :id_site_group
  #     visit:
  #       prefilters: site.groups.id_site_group = :id_site_group
  # site_group_edit:
  #   url: site_group_edit/:id_site_group
  #   layout:
  #     code: m_monitoring.site_group_edit
  #   objects:
  #     site_group:
  #       value: ":id_site_group"
