---
module:
  module_code: m_monitoring
  module_label: Gestionnaire de sites
  module_desc: Module de gestion de sites. (Vers une version 2 du module monitoring)
  module_picto: fa-puzzle-piece
  active_frontend: true
schemas:
- m_monitoring.site
- m_monitoring.observation
- m_monitoring.site_group
- m_monitoring.site_category
- m_monitoring.visit
- m_monitoring.sc_arbre_loge
- m_monitoring.sc_grotte
data:
  site:
    cruved: CRUD
    schema_name: m_monitoring.site
    map:
      bring_to_front: 'true'
  visit:
    cruved: CRUD
    schema_name: m_monitoring.visit
  site_group:
    cruved: CRUD
    schema_name: m_monitoring.site_group
    map:
      style:
        color: red
  observation:
    cruved: CRUD
    schema_name: m_monitoring.observation
  module:
    cruved: R
    schema_name: commons.module
  category:
    cruved: R
    schema_name: m_monitoring.site_category
tree:
  site:
    visit:
      observation:
pages:
  site_list:
    url: ''
    layout_name: m_monitoring.site_list
  site_group_details:
    url: site_group_details/:id_site_group
    layout_name: m_monitoring.site_group_details
    data:
      site_group:
        value: ":id_site_group"
        prefilters: id_site_group_=_:id_site_group
      site:
        prefilters: groups.id_site_group_=_:id_site_group
      visit:
        prefilters: site.groups.id_site_group_=_:id_site_group
  site_details:
    url: site_details/:id_site
    layout_name: m_monitoring.site_details
    data:
      site:
        value: ":id_site"
      visit:
        prefilters: id_site_=_:id_site
      module:
        prefilters: sites.id_site_=_:id_site
  visit_details:
    url: visit_details/:id_visit
    layout_name: m_monitoring.visit_details
    data:
      visit:
        value: ":id_visit"
      observation:
        prefilters: id_visit_=_:id_visit
  observation_details:
    url: observation_details/:id_observation
    layout_name: m_monitoring.observation_details
    data:
      observation:
        value: ":id_observation"
  site_group_edit:
    url: site_group_edit/:id_site_group
    layout_name: m_monitoring.site_group_edit
    data:
      site_group:
        value: ":id_site_group"
  site_edit:
    url: site_edit/:id_site
    layout_name: m_monitoring.site_edit
    data:
      site:
        value: ":id_site"
  visit_edit:
    url: visit_edit/:id_visit
    layout_name: m_monitoring.visit_edit
    data:
      visit:
        value: ":id_visit"
  observation_edit:
    url: observation_edit/:id_observation
    layout_name: m_monitoring.observation_edit
    data:
      observation:
        value: ":id_observation"
  site_group_create:
    url: site_group_create
    layout_name: m_monitoring.site_group_edit
  site_create:
    url: site_create
    layout_name: m_monitoring.site_edit
  visit_create:
    url: visit_create
    layout_name: m_monitoring.visit_edit
    data:
      visit:
        defaults:
          id_site: ":id_site"
          id_module: ":id_module"
  observation_create:
    url: observation_create
    layout_name: m_monitoring.observation_edit
    data:
      observation:
        defaults:
          id_visit: ":id_visit"
