type: schema
code: m_monitoring.sc_arbre_loge
title: schema site arbre à loge
description: >
    Définition du schema pour les données complémentaires
    aux site de catégorie 'Arbre à loge'

meta:
    sql_processing: true
    sql_schema_dot_table: pr_monitoring.sc_arbre_loge
    genre: M
    label: Donnée arbre à loge
    labels: Données arbre à loge
    label_field_name: id_site
    unique:
        - id_site
properties:
    id_site:
        type: integer
        title: Pk du site
        primary_key: true
        foreign_key: true
        schema_code: m_monitoring.site
    hauteur:
        type: number
        title: hauteur
    site:
        type: relation
        local_key: id_site
        relation_type: 1-1
        title: sites
        description: Site associé
        schema_code: m_monitoring.site
        backref: data_arbre_loge
