module:
    module_code: MODULES
    module_label: Module de module
    module_desc: Ne permet pas de compter les patates
    module_picto: fa-puzzle-piece
    active_frontend: false
data:
    ref_geo.area:
        cruved: R
    ref_geo.linear_group:
        cruved: R
    user.role:
        cruved: R
    user.organisme:
        cruved: R
    ref_nom.nomenclature:
        cruved: R
    commons.module:
        cruved: R
    meta.jdd:
        cruved: R
    tax.taxref:
        cruved: R
