type: module
code: __REF_MODULE_CODE__
title: Module '__REF_MODULE_CODE__'
description: Définition du module __REF_MODULE_CODE__ (ouverture des routes communes (cruved R seulement))
module:
    module_label: Module de module
    module_desc: MonitoringV2
    module_picto: fa-puzzle-piece
    active_frontend: false
objects:
    ref_geo.area:
        cruved: R
    ref_geo.linear_group:
        cruved: R
    user.role:
        cruved: R
    user.organisme:
        cruved: R
    ref_nom.nomenclature:
        cruved: R
    commons.module:
        cruved: R
    meta.jdd:
        cruved: R
    meta.ca:
        cruved: R
    tax.taxref:
        cruved: R
    tax.taxsearch:
        cruved: R
    syn.synthese:
        cruved: R