type: schema
code: ref_nom.nomenclature
title: Schema ref_nom.nomenclature
description: Définition du schema des nomenclatures

required:
  - id_type
  - cd_nomenclature
meta:
  schema_code: ref_nom.nomenclature
  autoschema: true
  unique:
    - id_type
    - cd_nomenclature
  import:
    copy:
      label_default:
        - label_fr
      definition_default:
        - definition_fr
  model_name: TNomenclatures
  sql_schema_dot_table: ref_nomenclatures.t_nomenclatures
  genre: F
  label: nomenclature
  table:
    columns:
      - cd_nomenclature
      - mnemonique
      - label_fr
      - nomenclature_type.mnemonique
      - nomenclature_type.label_fr
  label_field_name: label_fr
  relations:
    - nomenclature_type
