type: schema
code: ref_nom.nomenclature
title: Schema ref_nom.nomenclature
description: Définition du schema des nomenclatures

meta:
  schema_code: ref_nom.nomenclature
  unique:
    - id_type
    - cd_nomenclature
  import:
    copy:
      label_default:
        - label_fr
      definition_default:
        - definition_fr
  model: pypnnomenclature.models.TNomenclatures
  genre: F
  label: nomenclature
  table:
    columns:
      - cd_nomenclature
      - mnemonique
      - label_fr
      - nomenclature_type.mnemonique
      - nomenclature_type.label_fr
  label_field_name: label_fr
  title_field_name: definition_fr
  sort: label_fr
