type: schema
code: ref_nom.type
title: Schema ref_nom.type
description: Définition du schema des types de nomenclature

required:
  - mnemonique
meta:
  schema_code: ref_nom.type
  unique:
    - mnemonique
  import:
    copy:
      label_default:
        - label_fr
      definition_default:
        - definition_fr
  model: pypnnomenclature.models.BibNomenclaturesTypes
  genre: F
  label: nomenclature
  label_field_name: label_fr
