type: schema
code: syn.synthese
title: Schema syn.synthese
description: Définition du schema de la synthese

meta:
    schema_code: syn.synthese
    autoschema: true
    model: geonature.core.gn_synthese.models.Synthese
    genre: M
    label: element de la synthese
    labels: elements de la synthese
    label_field_name: cd_nom
    geometry_field_name: the_geom_4326
    unique:
        - id_source
        - entity_source_pk_value
    properties:
        entity_source_pk_value:
            type: string