type: schema
code: syn.source
title: Schema syn.source
description: Définition du schema des sources de la synthese

meta:
    model: geonature.core.gn_synthese.models.TSources
    genre: F
    label: source
    label_field_name: name_source
    unique:
        - name_source
