type: data
code: m_eole.category
title: Données categories éolien
description: Données de catégories en lien avec le module éolien (éoliennées, gîtes)

items:
  - schema_code: m_monitoring.site_category
    items:
      - name: Éolienne
        code: EOL
        description: Éolienne
      - name: Gîte chiroptère
        code: GIT
        description: Gîte à chiroptère
