type: data
code: m_eole.exemples
title: Données exemple éolien
description: Données exemple pour le module éolien

items:
  - schema_code: meta.ca
    items:
      - acquisition_framework_name: ca_chiro
        acquisition_framework_desc: ca_chiro
        acquisition_framework_start_date: '2022-01-01'
  - schema_code: meta.jdd
    items:
      - id_acquisition_framework: ca_chiro
        dataset_name: jdd_chiro_mortalite
        dataset_shortname: jdd_chiro_mortalite
        dataset_desc: jdd_chiro_mortalite
        marine_domain: false
        terrestrial_domain: false
  - schema_code: commons.module
    items:
    - module_code: m_chiro_mortalite
      module_label: Suivi de mortalité (Chiroptère)
      module_desc: Suivi de mortalité (Chiroptère)
      module_path: modules/m_chiro_mortalite
      datasets:
        - - ca_chiro
          - jdd_chiro_mortalite
      active_frontend: false
      active_backend: false
    - module_code: m_chiro_persistance
      module_label: Test de persistance (Chiroptère)
      module_desc: Test de persistance (Chiroptère)
      module_path: modules/m_chiro_persistance
      active_frontend: false
      active_backend: false
    - module_code: m_chiro_prospection_gite
      module_label: Prospection de gîte (Chiroptère)
      module_desc: Prospection de gîte (Chiroptère)
      module_path: modules/m_chiro_prospection_gite
      active_frontend: false
      active_backend: false
  - schema_code: m_monitoring.site_group
    items:
      - name: Parc éolien Balsiège
        code: PE_BALS
        id_digitiser: admin
        geom:
          type: Polygon
          coordinates:
            - - - 3.4673759995739277
                - 44.49548315848623
              - - 3.4644628094048717
                - 44.506572947923424
              - - 3.4756300383863263
                - 44.508305536976145
              - - 3.4872827990625908
                - 44.50276107073015
              - - 3.486311735672931
                - 44.494096786489486
              - - 3.4732023799120797
                - 44.48993747274379
        modules:
          - m_eole

      - name: Parc éolien Mende
        code: PE_MEND
        id_digitiser: admin
        geom:
          type: Polygon
          coordinates:
            - - - 3.489144561566553
                - 44.50947952767899
              - - 3.5001342387181693
                - 44.50646294245999
              - - 3.5054177373487327
                - 44.5058596066822
              - - 3.512603295486315
                - 44.509932001996766
              - - 3.5075311368009747
                - 44.509328702125785
              - - 3.5014022783895142
                - 44.51113858300466
              - - 3.4952734199780537
                - 44.51264677413824
              - - 3.489144561566553
                - 44.50947952767899
        modules:
          - m_eole
  - schema_code: m_monitoring.site
    items:
      - name: Éolienne 6m
        code: BALS_E6
        description: Éolienne diamètre 6
        id_digitiser: admin
        id_inventor: admin
        id_nomenclature_type_site: "4"
        id_site_category: EOL
        geom:
          type: Point
          coordinates:
            - 3.4744162091492035
            - 44.492696666009145
        groups:
          - PE_BALS
        modules:
          - m_eole
          - m_chiro_mortalite
          - m_chiro_persistance
      - name: Éolienne 3m
        code: BALS_E3
        description: Éolienne diamètre 3
        id_digitiser: admin
        id_inventor: admin
        id_nomenclature_type_site: "4"
        id_site_category: EOL
        geom:
          type: Point
          coordinates:
            - 3.4854461125251706
            - 44.50198876013555
        groups:
          - PE_BALS
        modules:
          - m_eole
          - m_chiro_mortalite
          - m_chiro_persistance
      - name: Éolienne 10m
        code: BALS_E10
        description: Éolienne diamètre 10
        id_digitiser: admin
        id_inventor: admin
        id_nomenclature_type_site: "4"
        id_site_category: EOL
        geom:
          type: Point
          coordinates:
            - 3.4689087618114605
            - 44.505307249979765
        groups:
          - PE_BALS
        modules:
          - m_eole
          - m_chiro_mortalite
          - m_chiro_persistance
      - name: Éolienne 5m
        code: MEND_E5
        description: Éolienne diamètre 5
        id_digitiser: admin
        id_inventor: admin
        id_nomenclature_type_site: "4"
        id_site_category: EOL
        geom:
          type: Point
          coordinates:
            - 3.4908881161146526
            - 44.50911573845749
        groups:
          - PE_MEND
        modules:
          - m_eole
          - m_chiro_mortalite
          - m_chiro_persistance
      - name: Éolienne 50m
        code: MEND_E50
        description: Éolienne diamètre 50
        id_digitiser: admin
        id_inventor: admin
        id_nomenclature_type_site: "4"
        id_site_category: EOL
        geom:
          type: Point
          coordinates:
            - 3.492103320799692
            - 44.50964362811489
        groups:
          - PE_MEND
        modules:
          - m_eole
          - m_chiro_mortalite
          - m_chiro_persistance
      - name: Gîte Mende 1
        code: MEND_G1
        description: Ruine
        id_digitiser: admin
        id_inventor: admin
        id_nomenclature_type_site: "4"
        id_site_category: GIT
        geom:
          type: Point
          coordinates:
            - 3.49891903403313
            - 44.50934197746752
        groups:
          - PE_MEND
        modules:
          - m_eole
          - m_chiro_prospection_gite
      - name: Gîte Mende 2
        code: MEND_G2
        description: Grotte
        id_digitiser: admin
        id_inventor: admin
        id_nomenclature_type_site: "1"
        id_site_category: GIT
        geom:
          type: Point
          coordinates:
            - 3.495801769841074
            - 44.50696642406411
        groups:
          - PE_MEND
        modules:
          - m_eole
          - m_chiro_prospection_gite
  - schema_code: m_monitoring.visit
    items:
      -
        id_site: BALS_E3
        date_min: '2022-01-01'
        observers:
            - admin
        id_dataset:
          - ca_chiro
          - jdd_chiro_mortalite
        id_module: m_chiro_mortalite

