site_filters_fields:
  display: tabs
  items:
    - label: Infos
      items:
        - code_passage_faune
        - nom_usuel_passage_faune
        - nomenclatures_ouvrage_materiaux
        - key: pi_ou_ps
          title: Passage inférieur / supérieur
          type: list_form
          items:
            - value: true
              label: Passage supérieur
            - value: false
              label: Passage inférieur

    - label: Localisation
      items:
        - key: region
          title: Région
          type: list_form
          return_object: "true"
          additional_fields:
            - area_code
          area_type: REG
          sort: area_name

        - key: departement
          title: Département
          type: list_form
          reload_on_search: true
          area_type: DEP
          return_object: true
          additional_fields:
            - area_code
          label_field_name: code_name
          sort: code_name
          filters: |
            __f__data?.region
              ? `area_code in ${utils.departementsForRegion(data.region.area_code).join(';')}`
              : null

        - key: commune
          reload_on_search: true
          title: Commune
          type: list_form
          area_type: COM
          label_field_name: name_code
          filters: |
            __f__data?.departement
              ? `area_code like ${data.departement.area_code}%`
              : data?.region
                ? utils.departementsForRegion(data.region.area_code)
                    .map(departementCode => `area_code like ${departementCode}%`)
                    .join(',|,')
                : null
          sort: area_name

        - key: infrastructure
          title: Infrastructure
          type: list_form
          object_code: ref_geo.linear_group
          module_code: __REF_MODULE_CODE__
          filters: linears.type.type_code = RTE
          sort: name
          reload_on_search: true
          page_size: 10

site_filters_defs:
  code_passage_faune:
    type: ilike
  nom_usuel_passage_faune:
    type: ilike
  code_ouvrage_gestionnaire:
    type: ilike
  region:
    field: areas.id_area
    key: id_area
  departement:
    field: areas.id_area
    key: id_area
  commune:
    field: areas.id_area
  infracode_passagestructure:
    field: linears.groups.id_group
  nomenclatures_ouvrage_materiaux:
    field: nomenclatures_ouvrage_materiaux.id_nomenclature

site_table_fields:
  - code_passage_faune
  - nom_usuel_passage_faune
  - label_infrastructures
  - label_communes

site_map_popup_fields:
  - id_passage_faune
  - code_passage_faune
  - nom_usuel_passage_faune
  - nomenclatures_ouvrage_type.label_fr
  - label_infrastructures

site_details_fields:
  display: tabs
  items:
    - label: Propriétés
      items:
        - title: Informations
          display: fieldset
          items:
            - direction: row
              items:
                - code_passage_faune
                - code_ouvrage_gestionnaire
                - nom_usuel_passage_faune
                - uuid_passage_faune
            - direction: row
              items:
                - date_creation_ouvrage
                - issu_requalification
                - date_requalification_ouvrage
        - display: fieldset
          key: actors
          type: array
          items:
            direction: row
            items:
              - role.nom_role
              - organisme.nom_organisme
              - nomenclature_type_actor.label_fr
        - direction: row
          items:
            - title: Référentiel
              display: fieldset
              items:
                - items:
                    - label_infrastructures
                    - label_communes
                    - label_departements
            - title: Localisation
              display: fieldset
              items:
                - direction: row
                  items:
                    - geom_x
                    - geom_y
                - items:
                    - pk
                    - pr
                    - pr_abs
        - title: Caractéristiques
          display: fieldset
          items:
            - direction: row
              items:
                - nomenclature_ouvrage_specificite.label_fr
                - nomenclatures_ouvrage_materiaux.label_fr
            - direction: row
              items:
                - nomenclatures_ouvrage_type.label_fr
                - key: nomenclatures_ouvrage_type.cd_nomenclature
                  hidden: true
                - key: ouvrage_type_autre
                  hidden: __f__!data.nomenclatures_ouvrage_type?.some(n => n.cd_nomenclature == 'AUT')
            - direction: row
              items:
                - pi_ou_ps
                - ouvrage_hydrau
        - title: Dimensions
          display: fieldset
          items:
            - direction: row
              items:
                - largeur_ouvrage
                - hauteur_ouvrage
                - longueur_franchissement
            - direction: row
              items:
                - largeur_dispo_faune
                - hauteur_dispo_faune
                - diametre
        - title: Banquette (Ouvrages hydrauliques)
          display: fieldset
          hidden: "__f__!data.ouvrage_hydrau"
          items:
            - direction: row
              items:
                - nomenclature_ouvrage_hydrau_position.label_fr
                - nomenclature_ouvrage_hydrau_banq_caract.label_fr
                - nomenclature_ouvrage_hydro_banq_type.label_fr
                - ouvrag_hydrau_tirant_air
    - label: __f__`Médias (${data?.medias?.length || 0})`
      items:
        title: Médias
        items:
          - type: medias
            key: medias

site_form_fields:
  display: tabs
  items:
    - label: Propriétés
      items:
        - hidden: true
          items:
            - geom
            - key: id_passage_faune
              required: false
        - title: Informations
          display: fieldset
          items:
            - direction: row
              items:
                - code_passage_faune
                - code_ouvrage_gestionnaire
                - nom_usuel_passage_faune
            - direction: row
              items:
                - date_creation_ouvrage
                - issu_requalification
                - date_requalification_ouvrage
        - title: Acteurs
          type: array
          key: actors
          display: fieldset
          items:
            direction: row
            items:
              - id_role
              - id_organism
              - id_nomenclature_type_actor
        - title: Localisation
          display: fieldset
          items:
            - direction: row
              items:
                - pk
                - pr
                - pr_abs
        - title: Caractéristiques
          display: fieldset
          items:
            - direction: row
              items:
                - key: pi_ou_ps
                  type: list_form
                  items:
                    - value: true
                      label: Passage supérieur
                    - value: false
                      label: Passage inférieur
                - ouvrage_hydrau
            - direction: row
              items:
                - key: id_nomenclature_ouvrage_specificite
                  type: list_form
                - key: nomenclatures_ouvrage_materiaux
                  type: list_form
                  multiple: true
                  return_object: true
            - direction: row
              items:
                - key: nomenclatures_ouvrage_type
                  type: list_form
                  multiple: true
                  return_object: true
                  additional_fields: ["cd_nomenclature"]
                - key: ouvrage_type_autre
                  description: __f__data.nomenclatures_ouvrage_type?.some(n => n.cd_nomenclature == 'AUT')
                  type: string
                  hidden: __f__!data.nomenclatures_ouvrage_type?.some(n => n.cd_nomenclature == 'AUT')
                  required: __f__data.nomenclatures_ouvrage_type?.some(n => n.cd_nomenclature == 'AUT')

        - title: Dimensions
          display: fieldset
          items:
            - direction: row
              items:
                - largeur_ouvrage
                - hauteur_ouvrage
                - longueur_franchissement
            - direction: row
              items:
                - largeur_dispo_faune
                - hauteur_dispo_faune
                - diametre
        - title: Banquette
          hidden: "__f__!data.ouvrage_hydrau"
          display: fieldset
          items:
            - direction: row
              items:
                - key: id_nomenclature_ouvrage_hydrau_position
                  type: list_form
                - key: id_nomenclature_ouvrage_hydrau_banq_type
                  type: list_form
            - direction: row
              items:
                - key: id_nomenclature_ouvrage_hydrau_banq_caract
                  type: list_form
                - ouvrag_hydrau_tirant_air
    - label: __f__ `Médias (${data?.medias?.length || 0})`
      title: Médias
      items:
        - type: dyn_form
          key: medias
          type_widget: medias
          schema_dot_table: pr_sipaf.t_passages_faune
          details: []
