type: module
code: m_sipaf
title: Module de gestion des passage à faune
description: Module de gestion des passage à faune

config_params: !include ./config.yml

module:
  module_label: Passages faune
  module_desc: Module permettant la visualisation et la gestion des passages à Faune de France
  module_picto: fa-puzzle-piece
  active_frontend: true

features:
  - m_sipaf.utils


objects:
  site:
    schema_code: m_sipaf.pf
    cruved: CRUDE

tree:
  pf:

pages_definition:
  site:
    list:
      root: true
    create:
      layout:
        code: m_sipaf.site_edit
    edit:
    details:
