type: schema
code: occtax.occurrence
title: Schema occtax.occurrence
description: Définition du schema occtax des occurrences

meta:
    autoschema: true
    model: occtax.models.TOccurrencesOccurrence
    genre: F
    label: occurrence
    label_field_name: cd_nom
    unique:
      - id_releve_occtax
      - cd_nom
    relations:
      - cor_counting_occtax