type: layout
code: m_monitoring.site_edit
title: Layout site edit
description: Layout pour l'édition d'un site
layout:
  height_auto: true
  direction: row
  items:
    - type: object
      object_code: site
      items:
        type: form
        direction: row
        items:
          - type: map
            key: __f__o.geometry_field_name(x)
            edit: true
            # geometry_type: o.geometry_type(x)
            gps: true
            hidden: __f__!o.geometry_field_name(x)
            zoom: 12
          - items:
            - title: __f__o.title_create_edit(x)
            - items:
              - hidden: true
                items:
                - id_site
              - code
              - name
              - description
              - key: id_site_category
                type: list_form
                title: Catégorie de site
                object_code: category
                module_code: m_monitoring
              - id_nomenclature_type_site
              - ownership
            - direction: row
              items:
                - flex: '0'
                  type: button
                  color: primary
                  title: Valider
                  icon: done
                  description: Enregistrer le contenu du formulaire
                  action: submit
                  disabled: __f__!(formGroup.valid )
                - flex: '0'
                  type: button
                  color: primary
                  title: Annuler
                  icon: refresh
                  description: "Annuler lédition"
                  action: cancel
                - flex: '0'
                  type: button
                  color: warn
                  title: Supprimer
                  icon: delete
                  description: Supprimer le passage à faune
                  hidden: __f__!o.is_action_allowed(x, 'D')
                  action:
                    type: modal
                    modal_name: delete
                - type: modal
                  modal_name: delete
                  title: Confirmer la suppression de l'élément
                  direction: row
                  items:
                    - type: button
                      title: Suppression
                      action: delete
                      icon: delete
                      color: warn
                    - type: button
                      title: Annuler
                      action: close
                      icon: refresh
                      color: primary


