type: layout
code: m_monitoring.site_details
title: Layout site details
description: Layout pour les details d'un site

context:
  module_code: m_monitoring
layout:
  height_auto: true
  direction: row
  items:
    - type: map
      items:
        - type: object
          display: geojson
          object_code: site
    - items:
        - type: breadcrumbs
          flex: "0"
        - object_code: site
          type: object
          items:
            - title: __f__o.title_details(x)
              items:
                - hidden: true
                  items:
                    - id_site
                    - ownership
                - code
                - name
                - description
                - type: button
                  color: primary
                  title: Éditer
                  description: __f__o.title_create_edit(x)
                  action: edit
                  hidden: __f__!o.is_action_allowed(x, 'U')
                  flex: "0"

        - display: tabs
          items:
            - label: "__f__o.tab_label(x)"
              object_code: visit
              items:
                - action: create
                  type: button
                  icon: add
                  color: primary
                  description: __f__o.title_create_edit(x)
                  flex: "0"
                  params: "__f__{ return {id_site: context.params.id_site}}"
                - type: object
                  display: table
                  hidden: __f__!context.nb_total;
