type: layout
code: m_monitoring.observation_details
title: Layout observation details
description: Layout pour les détails d'une observation

aliases:
  - &observation_fields_details
    - hidden:
      - id_observation
    - id_visit
    - cd_nom
    - visit.date_min
    - taxon.nom_vern
    - visit.site.name
    - visit.dataset.dataset_name
    - visit.observers.nom_complet

layout:
  height_auto: true
  items:
    - type: breadcrumbs
      flex: "0"
    - type: object
      object_code: observation
      items:
        - title:  __f__o.title_details(x)
          flex: "0"
        - overflow: true
          items: *observation_fields_details
        - code: m_monitoring.button_edit
          flex: "0"
