type: layout
title: Layout visit details
description: Layout pour les détails d'une visite
code: m_monitoring.visit_details
layout:
  height_auto: true
  items:
    - type: breadcrumbs
      flex: "0"
    - object_code: visit
      type: object
      items:
        - title:  __f__o.title_details(x)
          items:
            - site.name
            - module.module_label
            - date_min
            - nb_observations
            - digitiser.nom_complet
            - dataset.dataset_name
            - dataset.acquisition_framework.acquisition_framework_name
            - observers.nom_complet