type: layout
code: m_monitoring.site_list
title: Layout site list
description: Layout pour la liste de sites
layout:
  height_auto: true
  direction: row
  items:
    - type: map
      items:
        type: object
        display: geojson
        object_code: site
        items:
          - name
          - code
          - description
          - nomenclature_type_site.label_fr
          - category.name
    - type: object
      display: table
      sort: last_visit_date_min-
      object_code: site
      items:
        - code
        - name
        - category.name
        - nb_visits
        - last_visit_date_min
context:
  module_code: m_monitoring