type: layout
code: m_monitoring.observation_edit
title: Layout observation edit
description: Layout pour l'édition d'une observation
layout:
  height_auto: true
  direction: row
  items:
    - type: object
      display: form
      key: observation
