type: layout
code: m_monitoring.visit_edit
title: Layout visit edit
description: Layout pour l'édition d'une visite

layout:
  height_auto: true
  direction: row
  items:
    - type: object
      display: form
      key: visit
