type: layout
code: m_monitoring.site_details
title: Layout site details
description: Layout pour les details d'un site

context:
  module_code: m_monitoring
layout:
  height_auto: true
  direction: row
  items:
    - type: map
      items:
        - type: object
          display: geojson
          object_code: site
          value: 1
    - items:
        - type: breadcrumbs
          flex: "0"
        - object_code: site
          type: object
          display: properties
        - display: tabs
          items:
            - label: "__f__`Visites (${data.visit.filtered}/${data.visit.total})`"
              object_code: visit
              items:
                - object_code: visit
                  action: create
                  type: button
                  icon: add
                  color: primary
                  flex: "0"
                  params: "__f__{ return {id_site: data.site.value}}"
                - type: object
                  display: table
