type: layout
code: m_monitoring.module_details
title: Layout module details
description: Layout pour les détails d'un module
layout:
  height_auto: true
  direction: row
  items:
    - type: map
      items:
        - type: object
          object_code: site
          display: geojson
    - items:
        - type: breadcrumbs
          flex: "0"
        - code: utils.object_details
          template_params:
            object_code: "module"
            layout: __MODULE_DETAILS_FIELDS__
        - display: tabs
          items:
            - label: __f__o.tab_label(x)
              object_code: site
              items:
                - code: utils.button_create
                  flex: "0"
                - type: object
                  display: table
                  sort: last_visit_date_min-
                  items: __SITE_TABLE_FIELDS__