type: schema
code: tax.taxsearch
title: Schema tax.taxsearch
description: Définition du schema de taxonomie pour la recherche de taxon

meta:
    autoschema: true
    model: apptax.taxonomie.models.VMTaxrefListForautocomplete
    genre: F
    label: taxonomie
    label_field_name: search_name
    value_field_name: cd_nom
    unique:
        - cd_nom
