meta:
    schema_name: tax.taxref
    autoschema: true
    sql_schema_dot_table: taxonomie.taxref
    model_name: Taxref
    genre: F
    label: taxonomie
    label_field_name: nom_vern
    unique:
        - cd_nom
