type: schema
code: user.app
title: Schema user.app
description: Définition du schema pour les applications

meta:
    autoschema: true
    model_name: TApplications
    sql_schema_dot_table: utilisateurs.t_applications
    label: application
    label_field_name: nom_application
    genre: F
    unique:
        - code_application
