meta:
    schema_name: user.app
    autoschema: true
    model_name: TApplications
    sql_schema_dot_table: utilisateurs.t_applications
    label: application
    label_field_name: nom_application
    genre: F
    unique:
        - code_application
