type: schema
code: user.app_profil
title: Schema user.app_profil
description: Définition du schema pour les profils utilisateurs applications

meta:
    autoschema: true
    model_name: UserApplicationRight
    sql_schema_dot_table: utilisateurs.cor_role_app_profil
    label: application profil
    label_field_name: id_app
    genre: F
    unique:
        - id_profil
        - id_role
        - id_application
