type: schema
code: user.profil
title: Schema user.profil
description: Définition du schema pour les profils d'utilisateurs

meta:
    model: pypnusershub.db.models.Profils
    label: profil
    label_field_name: nom_profil
    genre: M
    unique:
        - code_profil
