type: schema
code: user.groupe
title: Schema user.groupe
description: Définition du schema pour les groupes d'utilisateurs

meta:
    model: geonature.core.users.models.CorRole
    label: groupe
    label_field_name: id_role_groupe
    genre: M
    unique:
        - id_role_utilisateur
        - id_role_groupe
properties:
    id_role_utilisateur:
        foreign_key: true
        schema_code: user.role
