type: schema
code: user.app_profil
title: Schema user.app_profil
description: Définition du schema pour les profils utilisateurs applications

meta:
    model: pypnusershub.db.models.UserApplicationRight
    label: application profil
    label_field_name: id_application
    genre: F
    unique:
        - id_profil
        - id_role
        - id_application
