type: layout
code: m_monitoring.site_details
title: Layout site details
description: Layout pour les details d'un site

context:
  module_code: m_monitoring
layout:
  height_auto: true
  direction: row
  items:
    - type: map
      items:
        - type: object
          display: geojson
          object_code: site
          prefilters: __f__`id_site = ${o.object(x, 'site').value}`
          popup_fields: __SITE_MAP_POPUP_FIELDS__

    - items:
        - type: breadcrumbs
          flex: "0"
        - code: utils.object_details
          template_params:
            object_code: site
            layout: __SITE_DETAILS_FIELDS__
        - display: tabs
          items:
            - label: __f__o.tab_label(x)
              object_code: visit
              items:
                - code: utils.button_create
                  flex: "0"
                - type: object
                  display: table
                  items: __VISIT_TABLE_FIELDS__
                  prefilters: __f__`id_site = ${o.object(x, 'site').value}`
                  sort: date_min-

