type: layout
code: m_monitoring.site_list
title: Layout site list
description: Layout pour la liste de sites

aliases:

layout:
  height_auto: true
  direction: row
  object_code: site
  items:
    - type: object
      display: filters
      flex: 1
      items:
        __SITE_FILTERS_FIELDS__
      filter_defs: __SITE_FILTERS_DEFS__

    - type: map
      flex: 2
      items:
        type: object
        display: geojson
        popup_fields: __SITE_MAP_POPUP_FIELDS__

    - items:
      - type: breadcrumbs
        flex: "0"
      - type: object
        flex: 2
        display: table
        sort: last_visit_date_min-
        items: __SITE_TABLE_FIELDS__

context:
  module_code: m_monitoring