type: layout
code: m_monitoring.site_list
title: Layout site list
description: Layout pour la liste de sites

aliases:

  - &site_map_popup_fields
    - name
    - code
    - description
    - nomenclature_type_site.label_fr
    - category.name

  - &site_table_fields
    - code
    - name
    - category.name
    - nb_visits
    - last_visit_date_min

  - &site_filter_defs
    category:
      field: category.id_category
    region:
      field: areas.id_area
      key: id_area
    departement:
      field: areas.id_area
      key: id_area
    commune:
      field: areas.id_area

layout:
  height_auto: true
  direction: row
  object_code: site
  items:
    - type: object
      display: filters
      flex: 1
      items:
        - code: m_monitoring.site_filters
      filter_defs: *site_filter_defs

    - type: map
      flex: 2
      items:
        type: object
        display: geojson
        popup_fields: *site_map_popup_fields

    - items:
      - type: breadcrumbs
        flex: "0"
      - type: object
        flex: 2
        display: table
        sort: last_visit_date_min-
        items: *site_table_fields

context:
  module_code: m_monitoring