type: layout
code: m_monitoring.site_details
title: Layout site details
description: Layout pour les details d'un site

context:
  module_code: m_monitoring
layout:
  height_auto: true
  direction: row
  items:
    - type: map
      items:
        - type: object
          display: geojson
          object_code: site
    - items:
        - type: breadcrumbs
          flex: "0"
        - object_code: site
          type: object
          items:
            - title: __f__o.title_details(x)
              items:
                - hidden: true
                  items:
                    - id_site
                    - ownership
                - code
                - name
                - description
                - nb_visits
                - code: m_monitoring.button_edit

        - display: tabs
          items:
            - label: "__f__o.tab_label(x)"
              object_code: visit
              items:
                - code: m_monitoring.button_create
                - type: object
                  display: table
                  items:
                    - site.name
                    - date_min
                    - nb_observations
                    - digitiser.nom_complet
                    - dataset.dataset_name
                    - observers.nom_complet
                    - module.module_label

                  sort: date_min-

