type: layout
code: m_monitoring.module_details
title: Layout module details
description: Layout pour les détails d'un module
layout:
  height_auto: true
  direction: row
  items:
    - type: map
      items:
        - type: object
          object_code: site
          display: geojson
    - items:
        - type: breadcrumbs
          flex: "0"
        - code: m_monitoring.object_details
          template_params:
            object_code: 'module'
            layout: __MODULE_DETAILS_FIELDS__
        - display: tabs
          items:
            - label: __f__o.tab_label(x)
              object_code: site
              items:
                - code: m_monitoring.button_create
                  flex: "0"
                - type: object
                  display: table
                  sort: last_visit_date_min-
                  items: __SITE_TABLE_FIELDS__

    #     - display: tabs
    #       items:
    #         - label: "__f__`Sites (${data.site.filtered}/${data.site.total})`"
    #           items:
    #             - key: site
    #               action: create
    #               type: button
    #               icon: add
    #               color: primary
    #               flex: "0"
    #               params: "__f__{ return {id_module: data.module.value}}"
    #             - type: object
    #               display: table
    #               key: site
    #         - label: "__f__`Jeu de données (${data.jdd.filtered}/${data.jdd.total})`"
    #           items:
    #             - type: object
    #               display: table
    #               key: jdd
