type: layout
code: m_monitoring.observation_edit
title: Layout observation edit
description: Layout pour l'édition d'une observation

layout:
  height_auto: true
  items:
    - type: breadcrumbs
    - type: object
      object_code: observation
      items:
        code: m_monitoring.object_form
        template_params:
          object_code: observation
          layout: __OBSERVATION_FORM_FIELDS__
