type: layout
code: m_monitoring.module_edit
title: Layout module edit
description: Layout pour l'édition d'un module
layout:
  height_auto: true
  items:
    code: utils.object_form
    template_params:
      object_code: module
      layout: __MODULE_FORM_FIELDS__
