type: layout
title: Layout visit details
description: Layout pour les détails d'une visite
code: m_monitoring.visit_details

layout:
  height_auto: true
  items:
    - type: breadcrumbs
      flex: "0"
    - items:
        direction: row
        items:
          - code: utils.object_details
            template_params:
              object_code: visit
              layout: __VISIT_DETAILS_FIELDS__
          - display: tabs
            items:
              - label: __f__o.tab_label(x)
                object_code: observation
                items:
                  - code: utils.button_create
                    flex: "0"
                  - type: object
                    display: table
                    items: __OBSERVATION_TABLE_FIELDS__
                    prefilters: __f__`id_visit = ${o.object(x, 'visit').value}`
                    sort: taxon.nom_vern

