
type: schema
code: m_sipaf.actor
title: schema acteur site
description: Définition du schema pour les acteurs liés aux sites
required:
    - id_passage_faune
    - id_nomenclature_type_actor
meta:
    autoschema: true
    schema_code: m_sipaf.actor
    # sql_processing: true
    # sql_schema_dot_table: pr_sipaf.cor_actor_pf
    model: m_sipaf.models.Actor
    genre: M
    label: Acteur
    label_field_name: id_nomenclature_type_actor
    unique:
        - id_nomenclature_type_actor
        - id_organism
        - id_role
        - id_passage_faune
properties:
    id_actor:
        type: integer
        primary_key: true
        title: ID actor
    id_passage_faune:
        type: integer
        foreign_key: true
        schema_code: m_sipaf.pf
        title: Passage_faune
        required: true
    id_organism:
        type: integer
        foreign_key: true
        schema_code: user.organisme
        title: Organisme
    id_role:
        type: integer
        foreign_key: true
        schema_code: user.role
        title: Utilisateur
    id_nomenclature_type_actor:
        type: integer
        foreign_key: true
        schema_code: ref_nom.nomenclature
        title: "Type d'acteur"
        nomenclature_type: PF_TYPE_ACTOR
    nomenclature_type_actor:
        type: relation
        relation_type: n-1
        local_key: id_nomenclature_type_actor
        schema_code: ref_nom.nomenclature
        title: "Type d'acteur"
    role:
        type: relation
        relation_type: n-1
        local_key: id_role
        schema_code: user.role
        title: Rôle
    organisme:
        type: relation
        relation_type: n-1
        local_key: id_organism
        schema_code: user.organisme
        title: Organisme
