type: schema
code: m_monitoring.sc_grotte
title: schema site grotte
description: >
    Définition du schema pour les données complémentaires
    aux site de catégorie 'Grotte'

meta:
    sql_processing: true
    sql_schema_dot_table: pr_monitoring.sc_grotte
    genre: M
    label: Donnée grotte
    labels: Données grotte
    label_field_name: id_site
    unique:
        - id_site
properties:
    id_site:
        type: integer
        title: Pk du site
        primary_key: true
        foreign_key: true
        schema_code: m_monitoring.site
    profondeur:
        type: number
        title: profondeur
    site:
        type: relation
        local_key: id_site
        relation_type: 1-1
        title: sites
        description: Site associé
        schema_code: m_monitoring.site
        backref: data_grotte
