type: module
code: m_monitoring_test_1
title: Module monitoring test 1
description: Module de test avec entrée par protocole

template_code: m_monitoring.protocol_template
template_params:
  module_code: m_monitoring_test_1
  module_label: Protocole test 1
  module_desc: Second module de test monitoring V2
  module_picto: fa-puzzle-piece
  active_frontend: false
