type: use_template
code: m_monitoring_test_1
title: Module monitoring test 1
description: Module de test avec entrée par protocole

template_code: m_monitoring.module_template
params:
  module_code: m_monitoring_test_1
  module_label: Monitest_1
  module_desc: Second module de test monitoring V2
  module_picto: fa-puzzle-piece
  active_frontend: false
