# module pour tester le templating de module
with_template:
  name: m_monitoring.module_template
  params:
    module_code: m_monitoring_test_1
    module_label: Monitest_1
    module_desc: Premier module de test monitoring V2
    module_picto: fa-puzzle-piece
    active_frontend: false
