required:
    - id_site
    - id_nomenclature_type_actor
meta:
    schema_name: m_monitoring.actor
    sql_processing: true
    sql_schema_dot_table: m_monitoring.cor_site_actor
    genre: M
    label: Acteur
    label_field_name: id_nomenclature_role_actor
    unique:
        - id_nomenclature_type_actor
        - id_organism
        - id_role
        - id_site
properties:
    id_actor:
        type: integer
        primary_key: true
        title: ID actor
    id_site:
        type: integer
        foreign_key: true
        schema_name: m_monitoring.site
        title: Site
        required: true
    id_organism:
        type: integer
        foreign_key: true
        schema_name: user.organisme
        title: Organisme
    id_role:
        type: integer
        foreign_key: true
        schema_name: user.role
        title: Utilisateur
    id_nomenclature_type_actor:
        type: integer
        foreign_key: true
        schema_name: ref_nom.nomenclature
        title: "Type d'acteur"
        nomenclature_type: PF_TYPE_ACTOR
    nomenclature_type_actor:
        type: relation
        relation_type: n-1
        local_key: id_nomenclature_type_actor
        schema_name: ref_nom.nomenclature
        title: "Type d'acteur"
    role:
        type: relation
        relation_type: n-1
        local_key: id_role
        schema_name: user.role
        title: Rôle
    organisme:
        type: relation
        relation_type: n-1
        local_key: id_organism
        schema_name: user.organisme
        title: Organisme
