type: schema
code: m_monitoring.observation
title: Schema observation
description: Définition du schema des observations de monitoring

meta:
    sql_processing: 'true'
    sql_schema_dot_table: m_monitoring.t_observations
    genre: F
    label: observation
    label_field_name: cd_nom
    unique:
        - cd_nom
        - id_visit
properties:
    id_observation:
        type: integer
        title: "Pk de l'observation"
        description: "Clé primaire de l'observaiton"
        primary_key: true
    cd_nom:
        type: integer
        foreign_key: true
        title: Taxon
        schema_code: tax.taxref
        description: "Taxon lié à l'observation"
    taxon:
        type: relation
        relation_type: n-1
        title: Taxon
        local_key: cd_nom
        schema_code: tax.taxref
        description: "Taxon lié à l'observation"
    id_digitiser:
        type: integer
        foreign_key: true
        schema_code: user.role
        title: Numérisateur
        description: Personne qui a saisi la donnée
    id_visit:
        type: integer
        foreign_key: true
        title: Visite
        description: "Visite associée à l'observation"
        schema_code: m_monitoring.visit
    observation_uuid:
        type: uuid
        title: UUID
    visit:
        type: relation
        relation_type: n-1
        schema_code: m_monitoring.visit
        local_key: id_visit
        description: "Visite associée à l'observation"
        title: Visite
    data:
        type: json
        description: "Données additionnelles de l'observation"
        title: Données additionnelles
details:
    layout:
        - id_visit
        - cd_nom
        - visit.date_min
        - taxon.nom_vern
        - visit.site.name
        - visit.dataset.dataset_name
        - visit.observers.nom_complet
form:
    layout:
        -
            hidden: true
            items:
                - id_visit
                -
                    key: id_digitiser
                    default: __f__context.current_user?.id_role
        -
            key: cd_nom
            type: list_form
            title: Taxon
            schema_code: tax.taxref
            page_size: 10
            reload_on_search: true
table:
    columns:
        - cd_nom
        - visit.date_min
        - taxon.nom_vern
