meta:
    schema_name: m_monitoring.site_category
    sql_processing: true
    sql_schema_dot_table: m_monitoring.bib_sites_category
    genre: F
    label: categorie des sites
    labels: categories des sites
    label_field_name: name
    unique:
        - code
properties:
    id_category:
        type: integer
        title: Pk du site
        primary_key: true
    name:
        type: string
        title: Nom du complément de site
        required: true
    code:
        type: string
        title: Code du complément de site
        required: true
    description:
        type: string
        title: Description du complément de site
        required: true
