meta:
    schema_name: m_monitoring.visit
    sql_processing: 'true'
    sql_schema_dot_table: m_monitoring.t_visits
    genre: F
    label: visite
    label_field_name: date_min
    unique:
        - id_site
        - date_min
properties:
    id_visit:
        type: integer
        title: "Pk de l'observation"
        description: Clé primaire de la visite
        primary_key: true
    uuid:
        type: uuid
        title: UUID
    date_min:
        type: date
        title: Date (min)
        description: Date (minimale) associée à la visite
        required: true
    date_max:
        type: date
        title: Date (max)
        description: Date (maximale) associée à la visite
    id_site:
        type: integer
        foreign_key: true
        title: Site
        description: Site associé à la visite
        schema_name: m_monitoring.site
    site:
        type: relation
        relation_type: n-1
        schema_name: m_monitoring.site
        local_key: id_site
        description: Site associé à la visite
        title: Site
    module:
        type: relation
        relation_type: n-1
        title: Protocole
        description: Protocole associé à la visite
        schema_name: commons.module
        local_key: id_module
    id_digitiser:
        type: integer
        foreign_key: true
        schema_name: user.role
        title: Numérisateur
        description: Personne qui a saisi la donnée
    digitiser:
        type: relation
        relation_type: n-1
        schema_name: user.role
        title: Numérisateur
        description: Personne qui a saisi la donnée
        local_key: id_digitiser
    observers:
        type: relation
        relation_type: n-n
        schema_name: user.role
        title: Observateurs
        description: Observateurs liés à la visite
        schema_dot_table: m_monitoring.cor_visit_observer
    id_dataset:
        type: integer
        foreign_key: true
        schema_name: meta.jdd
        title: Jeu de données
        description: Jeu de données associé à la visite
        required: true
    id_module:
        type: integer
        foreign_key: true
        schema_name: commons.module
        title: Protocole
        description: Protocole associé à la visite
        required: true
    dataset:
        type: relation
        relation_type: n-1
        schema_name: meta.jdd
        title: Jeu de données
        description: Jeu de données associé à la visite
        local_key: id_dataset
    data:
        type: json
        description: Données additionnelles du site
        title: Données additionnelles
    observations:
        type: relation
        relation_type: 1-n
        title: observations
        foreign_key: cd_nom
        description: Observations liées à la visite
        schema_name: m_monitoring.observation
    nb_observations:
        type: integer
        title: "Nombre d'observations"
        column_property: nb
        relation_key: observations
details:
    layout:
        - site.name
        - module.module_label
        - date_min
        - nb_observations
        - digitiser.nom_complet
        - dataset.dataset_name
        - dataset.acquisition_framework.acquisition_framework_name
        - observers.nom_complet
form:
    layout:
        -
            hidden: true
            items:
                - id_site
                - id_module
                -
                    key: id_digitiser
                    default: __f__meta.currentUser?.id_role
                    hidden: true
        -
            key: date_min
            default: __f__utils.today()
        - date_max
        -
            key: id_dataset
            type: list_form
            title: Jeu de données
            schema_name: meta.jdd
            page_size: 10
            reload_on_search: true
            filters: '__f__data.id_module && `modules.id_module = ${data.id_module}`'
        -
            key: observers
            type: list_form
            title: Observateurs
            schema_name: user.role
            multiple: true
            return_object: true
            filters: groupes.listes.code_liste = obsocctax
        -
            key: id_module
            type: list_form
            title: Protocole
            schema_name: commons.module
            filters: '__f__`sites.id_site = ${data.id_site}`'
table:
    columns:
        - site.name
        - date_min
        - nb_observations
        - digitiser.nom_complet
        - dataset.dataset_name
        - observers.nom_complet
    sort: date_min-
