type: data
code: m_sipaf.pf_test
title: Data utils m_sipaf
description: feature de testpour sipaf
items:
  - schema_code: m_sipaf.pf
    items:
      - uuid_passage_faune: 8a69f3af-125a-4b55-96d4-8b57c906dd59
        geom:
          type : 'Point'
          coordinates: [ 0, 45 ]
        actors:
          - id_role: admin
            id_nomenclature_type_actor: PRO