type: schema
code: perm.permission
title: Schema perm.permission
description: Définition du schema des permissions

meta:
  autoschema: true
  model: geonature.core.gn_permissions.models.CorRoleActionFilterModuleObject
  label: permission
  label_field_name: id_permssion
  genre: F
  unique:
    - id_role
    - id_module
    - id_action
    - id_object
