type: schema
code: perm.action
title: Schema perm.action
description: Définition du schema des actions

meta:
  autoschema: true
  model: geonature.core.gn_permissions.models.TActions
  label: action
  label_field_name: label_action
  genre: M
  unique:
    - code_action
