type: schema
code: commons.module
title: Schema commons.module
description: Définition du schema des modules

meta:
    autoschema: true
    model_name: TModules
    sql_schema_dot_table: gn_commons.t_modules
    label: module
    label_field_name: module_label
    genre: M
    relations:
        - datasets
    unique:
        - module_code
    check_cruved: false
properties:
    module_label:
        title: Nom du module
    module_code:
        title: Code du module
    module_desc:
        title: Description du module
details:
    layout:
        - module_code
        - module_label
        - module_desc
form:
    layout:
        - module_code
        - module_label
        - module_desc
table:
    columns:
        - module_code
        - module_label
        - module_desc
