type: schema
code: commons.media
title: Schema commons.media
description: Définition du schema des medias

meta:
  autoschema: true
  model: geonature.core.gn_commons.models.base.TMedias
  label: média
  label_field_name: title_fr
  genre: M
  unique:
    - id_table_location
    - title_fr
