type: schema
code: commons.cor_module_jdd
title: Schema commons.cor_module_jdd
description: Définition du schema du lien module jdd

meta:
    schema_code: commons.cor_module_jdd
    autoschema: true
    model_name: CorModuleDataset
    sql_schema_dot_table: gn_commons.cor_module_dataset
    label: module
    label_field_name: id_module
    genre: M
    unique:
        - id_module
        - id_dataset
