type: import
code: m_sipaf.pf_V1
title: Données d'exemple m_sipaf
description: import données d'exemple de passage à faune pour SIPAF
items:
  - object_code: user.organisme
    module_code: MODULATOR
    data: pf_V1.csv
    mapping: scripts/ppi_organism_V1.sql
  - object_code: site
    module_code: m_sipaf
    data: pf_V1.csv
    mapping: scripts/ppi_pf_V1.sql
    keep_raw: true
  - object_code: actor
    module_code: m_sipaf
    data: pf_V1.csv
    mapping: scripts/ppi_actor_V1.sql
    keep_raw: true
