type: import
code: ref_geo.route
title: import ref_geo.route
description: scenario d'import de données pour le ref_geo lineaire (route, autoroute)
items:
  - module_code: MODULATOR
    object_code: ref_geo.linear_type
    data: linear_type.csv
  - module_code: MODULATOR
    object_code: ref_geo.linear_group
    data: TRONCON_DE_ROUTE_NATIONALE_AUTOROUTE.csv
    mapping: scripts/ppi_groupe_route_na.sql
  - module_code: MODULATOR
    object_code: ref_geo.linear
    ref_geo.linear: ref_geo.linear
    data: TRONCON_DE_ROUTE_NATIONALE_AUTOROUTE.csv
    mapping: scripts/ppi_troncon_route_na.sql
    keep_raw: true
