#
module_code: m_eole
module:
  module_label: Modules de suivi éolien
  module_desc: POC pour le projet suivi éolien
  module_picto: fa-puzzle-piece
  active_frontend: true
dependencies:
    - m_monitoring
objects:
  parc:
    cruved: CRUD
    schema_name: m_monitoring.site_group
    label: Parc éolien
    labels: Parcs éolien
    prefilters: modules.id_module = :id_module
  gite:
    cruved: CRUD
    schema_name: m_monitoring.site
    label: Gîte chiroptère
    labels: Gîtes chiroptère
    prefilters:
      - category.code = GIT
      - modules.id_module = :id_module
    map:
      style:
        color: red
      bring_to_front: true
  eolienne:
    cruved: CRUD
    schema_name: m_monitoring.site
    label: Éolienne
    genre: F
    prefilters:
      - category.code = EOL
      - modules.id_module = :id_module
    map:
      style:
        color: green
      bring_to_front: true
  visite:
    cruved: CRUD
    schema_name: m_monitoring.site
  protocole:
    cruved: R
    schema_name: commons.module
  observation:
    cruved: CRUD
    schema_name: m_monitoring.observation

params:
  id_module:
    schema_name: commons.module
    value:
      module_code: m_eole

tree:
  parc:

pages:
  parc_list:
    url: ''
    layout_name: m_eole.parc_list
  parc_details:
    url: parc/:id_site_group
    layout_name: m_eole.parc_details

features:
  - m_eole.data
